select * from information_schema.columns where table_schema = 'callcenter'


select
'select top 40 * from
(' +
'select distinct  ' 
+'''+TABLE_SCHEMA+'''+' as TABLE_SCHEMA,' 
+'''+ TABLE_NAME+''' + ' as TABLE_NAME,' 
+'''+ COLUMN_NAME +'''+ ' as COLUMN_NAME,' 
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' +
') a union '
from  information_Schema.COLUMNS
where TABLE_schema = 'callcenter'
and COLUMN_NAME not in ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')
order by table_schema, table_name


select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Actions' as TABLE_NAME,'ActionId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionId] as nvarchar))),'"') as VALUE from CallCenter.[Actions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Actions' as TABLE_NAME,'ActionName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionName] as nvarchar))),'"') as VALUE from CallCenter.[Actions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Actions' as TABLE_NAME,'ActionSchema' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionSchema] as nvarchar))),'"') as VALUE from CallCenter.[Actions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Actions' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[Actions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'AgentScripts' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'AgentScripts' as TABLE_NAME,'ScriptDescription' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptDescription] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'AgentScripts' as TABLE_NAME,'ScriptID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptID] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'AgentScripts' as TABLE_NAME,'ScriptName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptName] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'AgentScripts' as TABLE_NAME,'ScriptType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptType] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'ActionProcessQueueId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'ActivityStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActivityStatus] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackCallType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackCallType] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackDate] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackMemberName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackMemberName] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackNumber] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackQueueId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackQueueId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackReason' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackReason] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackRefId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackRefId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'CallBackType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackType] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'NHMemberId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHMemberId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'PriorityLevel' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PriorityLevel] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'SourceActionProcessQueueId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SourceActionProcessQueueId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueue' as TABLE_NAME,'SourceAgentUserProfileId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SourceAgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueueVisibility' as TABLE_NAME,'AgentUserProfileId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueueVisibility' as TABLE_NAME,'CallBackQueueVisibilityId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackQueueVisibilityId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueueVisibility' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallBackQueueVisibility' as TABLE_NAME,'TransferAgentUserProfileId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TransferAgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'AgentUserProfileId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'AgentUserProfileName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AgentUserProfileName] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'CallBound' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBound] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'CallConversationId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'CallEndSummary' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallEndSummary] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'CallerNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerNumber] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'CallerTypeCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerTypeCode] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'CallingNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallingNumber] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'EndCallSummaryEnd' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndCallSummaryEnd] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'EndCallSummaryStart' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndCallSummaryStart] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'EndTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndTime] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'LinkedCallConversationId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LinkedCallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'MemberNHMemberId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberNHMemberId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'ProcessFlag' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessFlag] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallConversations' as TABLE_NAME,'StartTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StartTime] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallNotes' as TABLE_NAME,'CallConversationId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallNotes' as TABLE_NAME,'CallNoteId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallNoteId] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallNotes' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallNotes' as TABLE_NAME,'Note' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Note] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallNotes' as TABLE_NAME,'PageName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageName] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallPageEvents' as TABLE_NAME,'CallConversationId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallPageEvents' as TABLE_NAME,'CallPageEventId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallPageEventId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallPageEvents' as TABLE_NAME,'EventId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallPageEvents' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallPageEvents' as TABLE_NAME,'MemberAppointmentId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberAppointmentId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'CallPageEvents' as TABLE_NAME,'ReferenceIDsData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceIDsData] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'EventActions' as TABLE_NAME,'ActionId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionId] as nvarchar))),'"') as VALUE from CallCenter.[EventActions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'EventActions' as TABLE_NAME,'EventActionId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventActionId] as nvarchar))),'"') as VALUE from CallCenter.[EventActions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'EventActions' as TABLE_NAME,'EventId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventId] as nvarchar))),'"') as VALUE from CallCenter.[EventActions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'EventActions' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[EventActions]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'CallBound' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBound] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'EventCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'EventName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventName] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'EventTriggerBy' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventTriggerBy] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'Id' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Id] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'ParentId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentId] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'Events' as TABLE_NAME,'ReferenceIdType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceIdType] as nvarchar))),'"') as VALUE from CallCenter.[Events]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'OutboundCallTypes' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'OutboundCallTypes' as TABLE_NAME,'OutboundCallTypeCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutboundCallTypeCode] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'OutboundCallTypes' as TABLE_NAME,'OutboundCallTypeId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutboundCallTypeId] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'OutboundCallTypes' as TABLE_NAME,'OutboundCallTypeName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutboundCallTypeName] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSections' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSections' as TABLE_NAME,'ScriptID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptID] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSections' as TABLE_NAME,'ScriptSectionID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionID] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSections' as TABLE_NAME,'ScriptSectionTypeId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionTypeId] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSections' as TABLE_NAME,'SectionScriptDescription' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SectionScriptDescription] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSectionTypes' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSectionTypes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSectionTypes' as TABLE_NAME,'ScriptSectionTypeId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionTypeId] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSectionTypes]) a union 
select top 40 * from  (select distinct  'CallCenter' as TABLE_SCHEMA,'ScriptSectionTypes' as TABLE_NAME,'ScriptSectionTypeName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionTypeName] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSectionTypes]) a

select top 10 * from callcenter.CallConversations

select
'select top 40 * from
(' +
'select distinct  ' 
+'''+TABLE_SCHEMA+'|'    +'''+' as TABLE_SCHEMA,' 
+'''+ TABLE_NAME+ '|'     +''' + ' as TABLE_NAME,' 
+'''+ COLUMN_NAME+ '|'    +'''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' + ' where '+ 'ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar)))' + '='+ '@SearchPredicate' + 
+ ') a union '
from  information_Schema.COLUMNS
where TABLE_SCHEMA in ('callcenter')
--and TABLE_NAME = 'Events'
and COLUMN_NAME not in ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')
order by table_schema, table_name

--Record Count
select distinct

' select '+'''+Table_name+''' + ' as TABLE_NAME,' 
+ 'COUNT(*) ' + ' as RecordCount from ' 
+  Table_schema+'.'+ '['+TABLE_NAME+']'
+ ' union '
from information_schema.columns
where TABLE_SCHEMA in ('callcenter')

 select * from 
 (
 select 'Actions' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[Actions] union 
 select 'AgentScripts' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[AgentScripts] union 
 select 'CallBackQueue' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[CallBackQueue] union 
 select 'CallBackQueueVisibility' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[CallBackQueueVisibility] union 
 select 'CallConversations' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[CallConversations] union 
 select 'CallNotes' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[CallNotes] union 
 select 'CallPageEvents' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[CallPageEvents] union 
 select 'EventActions' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[EventActions] union 
 select 'Events' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[Events] union 
 select 'OutboundCallTypes' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[OutboundCallTypes] union 
 select 'ScriptSections' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[ScriptSections] union 
 select 'ScriptSectionTypes' as TABLE_NAME,COUNT(*)  as RecordCount from CallCenter.[ScriptSectionTypes]
 ) a
 order by 2 desc



declare @SearchPredicate nvarchar(50)
set @SearchPredicate = '7869881027'


select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionId] as nvarchar))),'"') as VALUE from CallCenter.[Actions] where ltrim(rtrim(cast([ActionId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionName] as nvarchar))),'"') as VALUE from CallCenter.[Actions] where ltrim(rtrim(cast([ActionName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionSchema|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionSchema] as nvarchar))),'"') as VALUE from CallCenter.[Actions] where ltrim(rtrim(cast([ActionSchema] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[Actions] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'AgentScripts|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'AgentScripts|' as TABLE_NAME,'ScriptDescription|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptDescription] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts] where ltrim(rtrim(cast([ScriptDescription] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'AgentScripts|' as TABLE_NAME,'ScriptID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptID] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts] where ltrim(rtrim(cast([ScriptID] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'AgentScripts|' as TABLE_NAME,'ScriptName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptName] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts] where ltrim(rtrim(cast([ScriptName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'AgentScripts|' as TABLE_NAME,'ScriptType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptType] as nvarchar))),'"') as VALUE from CallCenter.[AgentScripts] where ltrim(rtrim(cast([ScriptType] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'ActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'ActivityStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActivityStatus] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([ActivityStatus] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackCallType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackCallType] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackCallType] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackDate] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackDate] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackMemberName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackMemberName] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackMemberName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackNumber] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackNumber] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackQueueId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackQueueId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackReason|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackReason] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackReason] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackRefId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackRefId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackRefId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'CallBackType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackType] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([CallBackType] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'NHMemberId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHMemberId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([NHMemberId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'PriorityLevel|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PriorityLevel] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([PriorityLevel] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'SourceActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SourceActionProcessQueueId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([SourceActionProcessQueueId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueue|' as TABLE_NAME,'SourceAgentUserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SourceAgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueue] where ltrim(rtrim(cast([SourceAgentUserProfileId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueueVisibility|' as TABLE_NAME,'AgentUserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility] where ltrim(rtrim(cast([AgentUserProfileId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueueVisibility|' as TABLE_NAME,'CallBackQueueVisibilityId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBackQueueVisibilityId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility] where ltrim(rtrim(cast([CallBackQueueVisibilityId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueueVisibility|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallBackQueueVisibility|' as TABLE_NAME,'TransferAgentUserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TransferAgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallBackQueueVisibility] where ltrim(rtrim(cast([TransferAgentUserProfileId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'AgentUserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AgentUserProfileId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([AgentUserProfileId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'AgentUserProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AgentUserProfileName] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([AgentUserProfileName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'CallBound|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBound] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([CallBound] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'CallConversationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([CallConversationId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'CallEndSummary|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallEndSummary] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([CallEndSummary] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'CallerNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerNumber] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([CallerNumber] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'CallerTypeCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerTypeCode] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([CallerTypeCode] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'CallingNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallingNumber] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([CallingNumber] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'EndCallSummaryEnd|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndCallSummaryEnd] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([EndCallSummaryEnd] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'EndCallSummaryStart|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndCallSummaryStart] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([EndCallSummaryStart] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'EndTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndTime] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([EndTime] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'LinkedCallConversationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LinkedCallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([LinkedCallConversationId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'MemberNHMemberId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberNHMemberId] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([MemberNHMemberId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'ProcessFlag|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessFlag] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([ProcessFlag] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallConversations|' as TABLE_NAME,'StartTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StartTime] as nvarchar))),'"') as VALUE from CallCenter.[CallConversations] where ltrim(rtrim(cast([StartTime] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallNotes|' as TABLE_NAME,'CallConversationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes] where ltrim(rtrim(cast([CallConversationId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallNotes|' as TABLE_NAME,'CallNoteId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallNoteId] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes] where ltrim(rtrim(cast([CallNoteId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallNotes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallNotes|' as TABLE_NAME,'Note|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Note] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes] where ltrim(rtrim(cast([Note] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallNotes|' as TABLE_NAME,'PageName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageName] as nvarchar))),'"') as VALUE from CallCenter.[CallNotes] where ltrim(rtrim(cast([PageName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallPageEvents|' as TABLE_NAME,'CallConversationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallConversationId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents] where ltrim(rtrim(cast([CallConversationId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallPageEvents|' as TABLE_NAME,'CallPageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallPageEventId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents] where ltrim(rtrim(cast([CallPageEventId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallPageEvents|' as TABLE_NAME,'EventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents] where ltrim(rtrim(cast([EventId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallPageEvents|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallPageEvents|' as TABLE_NAME,'MemberAppointmentId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberAppointmentId] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents] where ltrim(rtrim(cast([MemberAppointmentId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'CallPageEvents|' as TABLE_NAME,'ReferenceIDsData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceIDsData] as nvarchar))),'"') as VALUE from CallCenter.[CallPageEvents] where ltrim(rtrim(cast([ReferenceIDsData] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'ActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionId] as nvarchar))),'"') as VALUE from CallCenter.[EventActions] where ltrim(rtrim(cast([ActionId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'EventActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventActionId] as nvarchar))),'"') as VALUE from CallCenter.[EventActions] where ltrim(rtrim(cast([EventActionId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'EventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventId] as nvarchar))),'"') as VALUE from CallCenter.[EventActions] where ltrim(rtrim(cast([EventId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[EventActions] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'CallBound|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBound] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([CallBound] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([EventCode] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventName] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([EventName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventTriggerBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventTriggerBy] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([EventTriggerBy] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'Id|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Id] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([Id] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'ParentId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentId] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([ParentId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'ReferenceIdType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceIdType] as nvarchar))),'"') as VALUE from CallCenter.[Events] where ltrim(rtrim(cast([ReferenceIdType] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'OutboundCallTypes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'OutboundCallTypes|' as TABLE_NAME,'OutboundCallTypeCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutboundCallTypeCode] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes] where ltrim(rtrim(cast([OutboundCallTypeCode] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'OutboundCallTypes|' as TABLE_NAME,'OutboundCallTypeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutboundCallTypeId] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes] where ltrim(rtrim(cast([OutboundCallTypeId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'OutboundCallTypes|' as TABLE_NAME,'OutboundCallTypeName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutboundCallTypeName] as nvarchar))),'"') as VALUE from CallCenter.[OutboundCallTypes] where ltrim(rtrim(cast([OutboundCallTypeName] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSections|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSections|' as TABLE_NAME,'ScriptID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptID] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections] where ltrim(rtrim(cast([ScriptID] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSections|' as TABLE_NAME,'ScriptSectionID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionID] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections] where ltrim(rtrim(cast([ScriptSectionID] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSections|' as TABLE_NAME,'ScriptSectionTypeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionTypeId] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections] where ltrim(rtrim(cast([ScriptSectionTypeId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSections|' as TABLE_NAME,'SectionScriptDescription|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SectionScriptDescription] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSections] where ltrim(rtrim(cast([SectionScriptDescription] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSectionTypes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSectionTypes] where ltrim(rtrim(cast([IsActive] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSectionTypes|' as TABLE_NAME,'ScriptSectionTypeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionTypeId] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSectionTypes] where ltrim(rtrim(cast([ScriptSectionTypeId] as nvarchar)))=@SearchPredicate) a union 
select top 40 * from  (select distinct  'CallCenter|' as TABLE_SCHEMA,'ScriptSectionTypes|' as TABLE_NAME,'ScriptSectionTypeName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScriptSectionTypeName] as nvarchar))),'"') as VALUE from CallCenter.[ScriptSectionTypes] where ltrim(rtrim(cast([ScriptSectionTypeName] as nvarchar)))=@SearchPredicate) a 