Select * from parseJSON_Modified('{"subdomain":"centralhealth"}',4,999,'{"subdomain":"centralhealth"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "SilverScript", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-223-0942", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"SilverScripts","accessCodes":"[SilverScript]"}',5,999,'{"carrierCode": "SilverScript", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-223-0942", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"SilverScripts","accessCodes":"[SilverScript]"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"eon","benefitValueSource":"nations","isManaged":true,"carrierCode":"eon","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-223-0703","clientLogoPlace":"Left"}',7,999,'{"subdomain":"eon","benefitValueSource":"nations","isManaged":true,"carrierCode":"eon","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-223-0703","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"dualprime","benefitValueSource":"nations","isManaged":true}',15,999,'{"subdomain":"dualprime","benefitValueSource":"nations","isManaged":true}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "aetna", "isTeleAudiologyEnabled": "true", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-253-3947", "subdomain": "aetna","benefitValueSource":"fis"}',16,999,'{"carrierCode": "aetna", "isTeleAudiologyEnabled": "true", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-253-3947", "subdomain": "aetna","benefitValueSource":"fis"}') Union ALL 
Select * from parseJSON_Modified('{    "subdomain": "ultimate",    "phone": "1-877-241-0303",    "isRegisterable": true,    "isManaged": true,    "isLoginRestricted": false,    "canSubscribe": false,    "benefitValueSource": "nations","restrictPayment":true,"disablePromotions":true,"showOTCGuidelines":true  ,"disclaimer":"Due to COVID-19, delivery times may take longer than usual.  Please know we are working hard to ensure your order is shipped as quickly as possible.  We thank you for your patience and understanding.","isTeleAudiologyEnabled":1,"carrierCode":"ultimate","languages":[],"showHeadPhonesText":true,"clientLogoPlace":"Left","dhePhone":"833-420-0818","useOldPortal":"true"}',14,999,'{    "subdomain": "ultimate",    "phone": "1-877-241-0303",    "isRegisterable": true,    "isManaged": true,    "isLoginRestricted": false,    "canSubscribe": false,    "benefitValueSource": "nations","restrictPayment":true,"disablePromotions":true,"showOTCGuidelines":true  ,"disclaimer":"Due to COVID-19, delivery times may take longer than usual.  Please know we are working hard to ensure your order is shipped as quickly as possible.  We thank you for your patience and understanding.","isTeleAudiologyEnabled":1,"carrierCode":"ultimate","languages":[],"showHeadPhonesText":true,"clientLogoPlace":"Left","dhePhone":"833-420-0818","useOldPortal":"true"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"bannerhealth","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',29,999,'{"subdomain":"bannerhealth","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"bluekc", "carrierCode":"bluekc"}',34,999,'{"subdomain":"bluekc", "carrierCode":"bluekc"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"cca","benefitValueSource":"nations","isManaged":true,"carrierCode":"cca","isTeleAudiologyEnabled":true}',62,999,'{"subdomain":"cca","benefitValueSource":"nations","isManaged":true,"carrierCode":"cca","isTeleAudiologyEnabled":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"fallonhealth"}',74,999,'{"subdomain":"fallonhealth"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"healthpartners"}',96,999,'{"subdomain":"healthpartners"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"independenthealth"}',106,999,'{"subdomain":"independenthealth"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"pacificsource"}',147,999,'{"subdomain":"pacificsource"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"presbyterianhealth","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',155,999,'{"subdomain":"presbyterianhealth","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"villagecare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',203,999,'{"subdomain":"villagecare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"notapplicable","carrierCode":"nations","dhePhone":"1-877-234-0811","isTeleAudiologyEnabled":true}',208,999,'{"subdomain":"notapplicable","carrierCode":"nations","dhePhone":"1-877-234-0811","isTeleAudiologyEnabled":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"notapplicable","carrierCode":"ExpressScripts","dhePhone":"877-214-0854","isTeleAudiologyEnabled":true,"languages":[      "English"    ],"pageType":"loginPage","clientLogoPlace":"Left"}',211,999,'{"subdomain":"notapplicable","carrierCode":"ExpressScripts","dhePhone":"877-214-0854","isTeleAudiologyEnabled":true,"languages":[      "English"    ],"pageType":"loginPage","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"ccai","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false,"carrierCode":"ccai","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-218-0073","clientLogoPlace":"Left"}',221,999,'{"subdomain":"ccai","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false,"carrierCode":"ccai","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-218-0073","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"hap","carrierCode":"hap"}',223,999,'{"subdomain":"hap","carrierCode":"hap"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"otcnetwork","isTeleAudiologyEnabled":true,"benefitValueSource":"incomm","isManaged":false,"isOTCCatalogCarrier":true,"isIncommCarrierEnabled":true}',258,999,'{"subdomain":"otcnetwork","isTeleAudiologyEnabled":true,"benefitValueSource":"incomm","isManaged":false,"isOTCCatalogCarrier":true,"isIncommCarrierEnabled":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"vibra","carrierCode":"vibra"}',267,999,'{"subdomain":"vibra","carrierCode":"vibra"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "avmed", "isTeleAudiologyEnabled": "true","clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-272-0587", "subdomain": "avmed"}',269,999,'{"carrierCode": "avmed", "isTeleAudiologyEnabled": "true","clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-272-0587", "subdomain": "avmed"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"bcbsri","benefitValueSource":"incomm","isManaged":true}',270,999,'{"subdomain":"bcbsri","benefitValueSource":"incomm","isManaged":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"capitalbluecross","carrierCode": "capitalbluecross", "isTeleAudiologyEnabled": "true","languages": ["English"], "dhePhone": "877-255-9851", "clientLogoPlace": "Left"}',271,999,'{"subdomain":"capitalbluecross","carrierCode": "capitalbluecross", "isTeleAudiologyEnabled": "true","languages": ["English"], "dhePhone": "877-255-9851", "clientLogoPlace": "Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"cchp","benefitValueSource":"nations","isManaged":true,"carrierCode":"cchp","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-234-7356","clientLogoPlace":"Left"}',273,999,'{"subdomain":"cchp","benefitValueSource":"nations","isManaged":true,"carrierCode":"cchp","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-234-7356","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"clearspring","benefitValueSource":"nations","isManaged":true,"carrierCode":"clearspring","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-221-4321","clientLogoPlace":"Left"}',274,999,'{"subdomain":"clearspring","benefitValueSource":"nations","isManaged":true,"carrierCode":"clearspring","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-221-4321","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode":"globalhealth","dhePhone":"877-241-9456","isTeleAudiologyEnabled":"true","subdomain":"notapplicable","languages":["English"],"clientLogoPlace":"Left"}',276,999,'{"carrierCode":"globalhealth","dhePhone":"877-241-9456","isTeleAudiologyEnabled":"true","subdomain":"notapplicable","languages":["English"],"clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"healthfirst","carrierCode":"healthfirst","dhePhone":"877-236-7027","isTeleAudiologyEnabled":true,"benefitValueSource":"incomm","isManaged":false,"clientLogoPlace":"Left"}',277,999,'{"subdomain":"healthfirst","carrierCode":"healthfirst","dhePhone":"877-236-7027","isTeleAudiologyEnabled":true,"benefitValueSource":"incomm","isManaged":false,"clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"optimahealth","carrierCode":"optima","isTeleAudiologyEnabled":"true","benefitValueSource":"nations","isManaged":true,"languages":["English"],"dhePhone":"877-206-4800","alwaysViewCatalog":"true","clientLogoPlace":"Left"}',278,999,'{"subdomain":"optimahealth","carrierCode":"optima","isTeleAudiologyEnabled":"true","benefitValueSource":"nations","isManaged":true,"languages":["English"],"dhePhone":"877-206-4800","alwaysViewCatalog":"true","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"reliance","ExecCarrierCode":"reliance","carrierCode":"reliance","dhePhone":"844-517-6863","isTeleAudiologyEnabled":"true","languages":["English"],"benefitValueSource":"nations","isManaged":true,"clientLogoPlace":"Left"}',280,999,'{"subdomain":"reliance","ExecCarrierCode":"reliance","carrierCode":"reliance","dhePhone":"844-517-6863","isTeleAudiologyEnabled":"true","languages":["English"],"benefitValueSource":"nations","isManaged":true,"clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"zing","ExecCarrierCode":"zinghealth","carrierCode":"zing","dhePhone":"877-246-1426","isTeleAudiologyEnabled":true,"languages":["English"],"benefitValueSource":"incomm","isManaged":true,"clientLogoPlace":"Left"}',281,999,'{"subdomain":"zing","ExecCarrierCode":"zinghealth","carrierCode":"zing","dhePhone":"877-246-1426","isTeleAudiologyEnabled":true,"languages":["English"],"benefitValueSource":"incomm","isManaged":true,"clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"connecticaremail"}',340,999,'{"subdomain":"connecticaremail"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"notapplicable","benefitValueSource":"NULL","isManaged":false}',285,999,'{"subdomain":"notapplicable","benefitValueSource":"NULL","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"connecticare","carrierCode":"connecticare","isTeleAudiologyEnabled":false,"parentCarrierId":258,"alwaysViewCatalog":false,"canSubscribe":false,"disablePromotions":false,"disclaimer":false,"isLoginRestricted":false,"isRegisterable":false,"phone":"844-432-4327","showHeadPhonesText":false,"showOTCGuidelines":false,"useOldPortal":false,"clientLogoName":"connecticare_logo.png"}',292,999,'{"subdomain":"connecticare","carrierCode":"connecticare","isTeleAudiologyEnabled":false,"parentCarrierId":258,"alwaysViewCatalog":false,"canSubscribe":false,"disablePromotions":false,"disclaimer":false,"isLoginRestricted":false,"isRegisterable":false,"phone":"844-432-4327","showHeadPhonesText":false,"showOTCGuidelines":false,"useOldPortal":false,"clientLogoName":"connecticare_logo.png"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"emblemhealth","parentCarrierId":258}',293,999,'{"subdomain":"emblemhealth","parentCarrierId":258}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"notapplicable", "carrierCode": "",  "isTeleAudiologyEnabled": "true", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-232-7013"}',296,999,'{"subdomain":"notapplicable", "carrierCode": "",  "isTeleAudiologyEnabled": "true", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-232-7013"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"connecticaremail"}',297,999,'{"subdomain":"connecticaremail"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"emblemhealthmail"}',298,999,'{"subdomain":"emblemhealthmail"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"geisinger","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',299,999,'{"subdomain":"geisinger","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"brighthealthplan","parentCarrierId":258,"benefitValueSource":"visa","isManaged":false}',300,999,'{"subdomain":"brighthealthplan","parentCarrierId":258,"benefitValueSource":"visa","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"fideliscare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',301,999,'{"subdomain":"fideliscare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"americanhealthadvantage"}',332,999,'{"subdomain":"americanhealthadvantage"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"alignment","benefitValueSource":"incomm","isManaged":true,"carrierCode":"alignment","isTeleAudiologyEnabled":true}',302,999,'{"subdomain":"alignment","benefitValueSource":"incomm","isManaged":true,"carrierCode":"alignment","isTeleAudiologyEnabled":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"bmchp","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',303,999,'{"subdomain":"bmchp","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"prominence","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',304,999,'{"subdomain":"prominence","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"icare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',305,999,'{"subdomain":"icare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"alohacare","benefitValueSource":"incomm","isManaged":false,"parentCarrierId":258}',331,999,'{"subdomain":"alohacare","benefitValueSource":"incomm","isManaged":false,"parentCarrierId":258}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"astivahealth","benefitValueSource":"nations","isManaged":true,"carrierCode":"astivahealth","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-230-4626","clientLogoPlace":"Left"}',334,999,'{"subdomain":"astivahealth","benefitValueSource":"nations","isManaged":true,"carrierCode":"astivahealth","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-230-4626","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"baycareplus","benefitValueSource":"nations","isManaged":true}',336,999,'{"subdomain":"baycareplus","benefitValueSource":"nations","isManaged":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"bcbsm","parentCarrierId":258,"benefitValueSource":"incomm"}',337,999,'{"subdomain":"bcbsm","parentCarrierId":258,"benefitValueSource":"incomm"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"dignityhealthplan","benefitValueSource":"nations","isManaged":true}',341,999,'{"subdomain":"dignityhealthplan","benefitValueSource":"nations","isManaged":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"emblemhealthmail"}',342,999,'{"subdomain":"emblemhealthmail"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"experiencehealthnc","benefitValueSource":"nations","isManaged":true,"carrierCode":"experiencehealthnc"}',343,999,'{"subdomain":"experiencehealthnc","benefitValueSource":"nations","isManaged":true,"carrierCode":"experiencehealthnc"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"integra","benefitValueSource":"incomm","isManaged":false,"parentCarrierId":258}',344,999,'{"subdomain":"integra","benefitValueSource":"incomm","isManaged":false,"parentCarrierId":258}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"kansashealthadvantage"}',345,999,'{"subdomain":"kansashealthadvantage"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"cpct","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',348,999,'{"subdomain":"cpct","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"thpmp","parentCarrierId":258}',349,999,'{"subdomain":"thpmp","parentCarrierId":258}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"wellcare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',352,999,'{"subdomain":"wellcare","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"notapplicable","dhePhone":"877-246-6968","isTeleAudiologyEnabled":true,"languages":["English"],"clientLogoPlace":"Left","pageType":"loginPage"}',354,999,'{"subdomain":"notapplicable","dhePhone":"877-246-6968","isTeleAudiologyEnabled":true,"languages":["English"],"clientLogoPlace":"Left","pageType":"loginPage"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"nextbluend","benefitValueSource":"nations","isManaged":true,"carrierCode":"nextbluend","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-246-6764","clientLogoPlace":"Left"}',355,999,'{"subdomain":"nextbluend","benefitValueSource":"nations","isManaged":true,"carrierCode":"nextbluend","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-246-6764","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"vba","benefitValueSource":"nations","isManaged":true,"carrierCode":"vba","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-246-6764","clientLogoPlace":"Left"}',356,999,'{"subdomain":"vba","benefitValueSource":"nations","isManaged":true,"carrierCode":"vba","isTeleAudiologyEnabled":"true","languages":["English"],"dhePhone":"877-246-6764","clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"notapplicable","carrierCode": "carefirst", "isTeleAudiologyEnabled": "true","languages": ["English"], "dhePhone": "877-234-6131", "clientLogoPlace": "Left"}',357,999,'{"subdomain":"notapplicable","carrierCode": "carefirst", "isTeleAudiologyEnabled": "true","languages": ["English"], "dhePhone": "877-234-6131", "clientLogoPlace": "Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"americanhealthadvantage","carrierCode":"americanhealthadvantage"}',358,999,'{"subdomain":"americanhealthadvantage","carrierCode":"americanhealthadvantage"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"ibx","benefitValueSource":"incomm","parentCarrierId":258}',359,999,'{"subdomain":"ibx","benefitValueSource":"incomm","parentCarrierId":258}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "clevercare", "isTeleAudiologyEnabled": "true", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-250-3531", "subdomain": "notapplicable"}',360,999,'{"carrierCode": "clevercare", "isTeleAudiologyEnabled": "true", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-250-3531", "subdomain": "notapplicable"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"hfhp","parentCarrierId":258,"benefitValueSource":"wex","isManaged":false}',362,999,'{"subdomain":"hfhp","parentCarrierId":258,"benefitValueSource":"wex","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"ahplan","parentCarrierId":258,"benefitValueSource":"wex","isManaged":false}',363,999,'{"subdomain":"ahplan","parentCarrierId":258,"benefitValueSource":"wex","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "IHdiscount", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-276-8392", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"InnovationHealth","accessCodes":"[InnovationHealth]"}',364,999,'{"carrierCode": "IHdiscount", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-276-8392", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"InnovationHealth","accessCodes":"[InnovationHealth]"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "AetnaMA", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-253-3947", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AetnaMALoginPage","accessCodes":"[AetnaMA]"}',365,999,'{"carrierCode": "AetnaMA", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-253-3947", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AetnaMALoginPage","accessCodes":"[AetnaMA]"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "AetnaDiscount", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-274-7931", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AetnaPDPLoginPage","accessCodes":"[AetnaPDP]"}',366,999,'{"carrierCode": "AetnaDiscount", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-274-7931", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AetnaPDPLoginPage","accessCodes":"[AetnaPDP]"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"floridabluemedicare","carrierCode":"floridabluemedicare","dhePhone":"877-232-7013","isTeleAudiologyEnabled":true,"languages":["English"],"clientLogoPlace":"Left"}',367,999,'{"subdomain":"floridabluemedicare","carrierCode":"floridabluemedicare","dhePhone":"877-232-7013","isTeleAudiologyEnabled":true,"languages":["English"],"clientLogoPlace":"Left"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"fhcpmedicare","carrierCode":"fhcpmedicare", "isTeleAudiologyEnabled":"true","clientLogoPlace":"Left", "languages":["English"],"dhePhone":"877-234-8167"}',368,999,'{"subdomain":"fhcpmedicare","carrierCode":"fhcpmedicare", "isTeleAudiologyEnabled":"true","clientLogoPlace":"Left", "languages":["English"],"dhePhone":"877-234-8167"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "IHdiscount", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-276-8392", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"InnovationHealth"}',370,999,'{"carrierCode": "IHdiscount", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-276-8392", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"InnovationHealth"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "NVA", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-272-6483", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AccessCodeLoginPage", "accessCodes":"[NVA823]"}',371,999,'{"carrierCode": "NVA", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-272-6483", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AccessCodeLoginPage", "accessCodes":"[NVA823]"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"demo","benefitValueSource":"fis","isManaged":true,"carrierCode":"demo"}',372,999,'{"subdomain":"demo","benefitValueSource":"fis","isManaged":true,"carrierCode":"demo"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"elderplan","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}',373,999,'{"subdomain":"elderplan","parentCarrierId":258,"benefitValueSource":"incomm","isManaged":false}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "CASEBP", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-259-4083", "alwaysViewCatalog": true, "subdomain": "notapplicable"}',376,999,'{"carrierCode": "CASEBP", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-259-4083", "alwaysViewCatalog": true, "subdomain": "notapplicable"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "universityofdayton", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-260-2306", "alwaysViewCatalog": true, "subdomain": "notapplicable"}',377,999,'{"carrierCode": "universityofdayton", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-260-2306", "alwaysViewCatalog": true, "subdomain": "notapplicable"}') Union ALL 
Select * from parseJSON_Modified('{"carrierCode": "cayugahealthsystem", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-260-1617", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AccessCodeLoginPage", "accessCodes":"[CAYUGA472]"}',378,999,'{"carrierCode": "cayugahealthsystem", "isTeleAudiologyEnabled": "true", "isRegisterable": false, "isManaged": false, "isLoginRestricted": false, "benefitValueSource": "nations", "clientLogoPlace": "Left", "languages": ["English"], "dhePhone": "877-260-1617", "alwaysViewCatalog": true, "subdomain": "notapplicable","pageType":"AccessCodeLoginPage", "accessCodes":"[CAYUGA472]"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"alignmentpartners","benefitValueSource":"fis","isManaged":true,"carrierCode":"alignmentpartners"}',379,999,'{"subdomain":"alignmentpartners","benefitValueSource":"fis","isManaged":true,"carrierCode":"alignmentpartners"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"molina","benefitValueSource":"fis","isManaged":true,"carrierCode":"molina"}',380,999,'{"subdomain":"molina","benefitValueSource":"fis","isManaged":true,"carrierCode":"molina"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"careoregonadvantage","benefitValueSource":"nations","isManaged":true}',381,999,'{"subdomain":"careoregonadvantage","benefitValueSource":"nations","isManaged":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"brighthealthcare","carrierCode":"brighthealthcare"}',382,999,'{"subdomain":"brighthealthcare","carrierCode":"brighthealthcare"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"georgiahealthadvantage"}',383,999,'{"subdomain":"georgiahealthadvantage"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"bnd"}',384,999,'{"subdomain":"bnd"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"chp"}',385,999,'{"subdomain":"chp"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"hapempowered","carrierCode":"hapempowered"}',386,999,'{"subdomain":"hapempowered","carrierCode":"hapempowered"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"newhanoverhealthadvantage","carrierCode":"newhanoverhealthadvantage"}',387,999,'{"subdomain":"newhanoverhealthadvantage","carrierCode":"newhanoverhealthadvantage"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"virginiapremier","carrierCode":"virginiapremier","isTeleAudiologyEnabled":true}',388,999,'{"subdomain":"virginiapremier","carrierCode":"virginiapremier","isTeleAudiologyEnabled":true}') Union ALL 
Select * from parseJSON_Modified('{"isTeleAudiologyEnabled":true,"carrierCode":"vp"}',389,999,'{"isTeleAudiologyEnabled":true,"carrierCode":"vp"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"wellmarkma","carrierCode":"wellmarkma","isTeleAudiologyEnabled":true}',390,999,'{"subdomain":"wellmarkma","carrierCode":"wellmarkma","isTeleAudiologyEnabled":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"alterwood"}',391,999,'{"subdomain":"alterwood"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"otcdemo","benefitValueSource":"nations","isManaged":true}',392,999,'{"subdomain":"otcdemo","benefitValueSource":"nations","isManaged":true}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"flexdemo","benefitValueSource":"fis","isManaged":"true","carrierCode":"flexdemo"}',393,999,'{"subdomain":"flexdemo","benefitValueSource":"fis","isManaged":"true","carrierCode":"flexdemo"}') Union ALL 
Select * from parseJSON_Modified('{"subdomain":"alignsanfordhealthplan", "carrierCode":"alignsanfordhealthplan"}',399,999,'{"subdomain":"alignsanfordhealthplan", "carrierCode":"alignsanfordhealthplan"}')