select * from information_schema.SCHEMATA order by schema_name

select * from information_schema.TABLES where TABLE_SCHEMA like 'FreedomH'

select top 10 * from freedomH.AFC_Nations_OTC_Orders
select top 10 * from freedomH.AFC_Nations_OTC_RAW
select top 10 * from freedomH.AFC_Nations_OTC_STG

select * from information_schema.columns where table_schema = 'FreedomH'

select
'select top 40 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+'|'    +''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+ '|'     +'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME+ '|'    +''''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' +
') a union '
from  information_Schema.COLUMNS
where table_schema = 'freedomH' and table_name in 
('AFC_Nations_OTC_Orders','AFC_Nations_OTC_RAW','AFC_Nations_OTC_STG')
and column_name not in ('CreateDate', 'ModifyDate', 'CreateUser', 'ModifyUser')
and data_type in ('nvarchar','bigint','datetime2','bit','varchar','datetime','int','decimal') --'varbinary' 'uniqueidentifier' removed

select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'FreedomH_OrderItem_ID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FreedomH_OrderItem_ID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'MemberID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'OrderID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'OrderDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_Address1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_Address2|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_City|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_State|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_ZIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_COUNTRY|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ProductID_AFC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProductID_AFC] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ProviderID_Vendor|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'Product_Name|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Product_Name] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'PartOrderedQty|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PartOrderedQty] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'Nation_Price|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Nation_Price] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'RecordLoadDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordLoadDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'FreedomH_STG_ID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FreedomH_STG_ID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'OrderStatusCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderStatusCode] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ACK_IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ACK_IsProcessed] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ACK_FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ACK_FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ACK_SentDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ACK_SentDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'TrackingNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TrackingNumber] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ClientResponse_IsSent|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientResponse_IsSent] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ClientResponse_FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientResponse_FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ClientResponse_SentDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientResponse_SentDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'File_Date|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([File_Date] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'MemberID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'OrderID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'OrderDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_Address1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_Address2|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_City|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_State|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_ZIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_COUNTRY|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'ProductID_AFC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProductID_AFC] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'ProviderID_Vendor|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'Product_Name|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Product_Name] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'PartOrderedQty|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PartOrderedQty] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'Nation_Price|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Nation_Price] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'File_Date|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([File_Date] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'FreedomH_STG_ID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FreedomH_STG_ID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'MemberID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'OrderID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'OrderDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_Address1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_Address2|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_City|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_State|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_ZIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_COUNTRY|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'ProductID_AFC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProductID_AFC] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'ProviderID_Vendor|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'Product_Name|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Product_Name] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'PartOrderedQty|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PartOrderedQty] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'Nation_Price|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Nation_Price] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'RecordLoadDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordLoadDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'File_Date|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([File_Date] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG]) a


/*
declare @SearchPredicate nvarchar(50)
set @SearchPredicate = 'Mobile Hearing Aids'
*/

select
'select top 40 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+'|'    +''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+ '|'     +'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME+ '|'    +''''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' + ' where '+ 'ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar)))' + ' like '+ '@SearchPredicate' + 
+ ') a union '
from  information_Schema.COLUMNS
where table_schema = 'freedomH' and table_name in 
('AFC_Nations_OTC_Orders','AFC_Nations_OTC_RAW','AFC_Nations_OTC_STG')
and column_name not in ('CreateDate', 'ModifyDate', 'CreateUser', 'ModifyUser') --'varbinary' 'uniqueidentifier' removed


declare @SearchPredicate nvarchar(50)
set @SearchPredicate = '%Ruskin%'

select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'FreedomH_OrderItem_ID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FreedomH_OrderItem_ID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([FreedomH_OrderItem_ID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'MemberID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([MemberID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'OrderID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([OrderID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'OrderDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([OrderDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_Address1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_Address2|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_City|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_State|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_ZIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'SHIP_TO_COUNTRY|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ProductID_AFC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProductID_AFC] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ProductID_AFC] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ProviderID_Vendor|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'Product_Name|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Product_Name] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([Product_Name] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'PartOrderedQty|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PartOrderedQty] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([PartOrderedQty] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'Nation_Price|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Nation_Price] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([Nation_Price] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'RecordLoadDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordLoadDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([RecordLoadDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'FreedomH_STG_ID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FreedomH_STG_ID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([FreedomH_STG_ID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'OrderStatusCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderStatusCode] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([OrderStatusCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ACK_IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ACK_IsProcessed] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ACK_IsProcessed] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ACK_FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ACK_FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ACK_FileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ACK_SentDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ACK_SentDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ACK_SentDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ShipDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShipDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ShipDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'TrackingNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TrackingNumber] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([TrackingNumber] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ClientResponse_IsSent|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientResponse_IsSent] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ClientResponse_IsSent] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ClientResponse_FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientResponse_FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ClientResponse_FileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'ClientResponse_SentDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientResponse_SentDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([ClientResponse_SentDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_Orders|' as TABLE_NAME,'File_Date|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([File_Date] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_Orders] where ltrim(rtrim(cast([File_Date] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'MemberID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([MemberID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'OrderID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([OrderID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'OrderDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([OrderDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_Address1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_Address2|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_City|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_State|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_ZIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'SHIP_TO_COUNTRY|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'ProductID_AFC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProductID_AFC] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([ProductID_AFC] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'ProviderID_Vendor|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'Product_Name|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Product_Name] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([Product_Name] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'PartOrderedQty|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PartOrderedQty] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([PartOrderedQty] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'Nation_Price|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Nation_Price] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([Nation_Price] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([FileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_RAW|' as TABLE_NAME,'File_Date|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([File_Date] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_RAW] where ltrim(rtrim(cast([File_Date] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'FreedomH_STG_ID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FreedomH_STG_ID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([FreedomH_STG_ID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'MemberID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([MemberID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'OrderID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([OrderID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'OrderDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([OrderDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_FirstName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_MiddleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_LastName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_Address1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_Address1] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_Address2|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_Address2] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_City|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_City] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_State|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_State] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_ZIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_ZIP] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'SHIP_TO_COUNTRY|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([SHIP_TO_COUNTRY] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'ProductID_AFC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProductID_AFC] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([ProductID_AFC] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'ProviderID_Vendor|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([ProviderID_Vendor] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'Product_Name|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Product_Name] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([Product_Name] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'PartOrderedQty|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PartOrderedQty] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([PartOrderedQty] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'Nation_Price|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Nation_Price] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([Nation_Price] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([IsProcessed] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'RecordLoadDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordLoadDate] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([RecordLoadDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'FileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileName] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([FileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'FreedomH|' as TABLE_SCHEMA,'AFC_Nations_OTC_STG|' as TABLE_NAME,'File_Date|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([File_Date] as nvarchar))),'"') as VALUE from FreedomH.[AFC_Nations_OTC_STG] where ltrim(rtrim(cast([File_Date] as nvarchar))) like @SearchPredicate) a