select * from information_schema.columns where table_schema like '%flex%'

select distinct table_name from information_schema.columns where TABLE_SCHEMA in ('flex')
select distinct ''''+table_name+''''+ ',' from information_schema.columns where TABLE_SCHEMA in ('flex')

select * from information_schema.columns where table_schema = 'flex'

-- TableNames
--('BatchHeaderTrailer','DetailRecord','FileFailure','FileHeaderTrailer','FISFieldStartEndPositions','FISWalletMapping',,'FISWalletMapping_STAGE','FISWallets','FlipCards','StgReturnFileData')

--Other tables
--,'temp_CardBenefitLoad','FISWalletMapping_STAGE_bkp_20220428','FISWalletMapping_bkp_20211231_beforeALGN', 'DetailRecord_bkp_20220623_Aetna_COVID', 'FISFieldStartEndPositions_bkp_20210914','FISFieldStartEndPositions_bkp_20211103_before_TRIM','FISFieldStartEndPositions_bkp_20220604_before_DF', 'FISFieldStartEndPositions_temp'



/*
('BatchHeaderTrailer','DetailRecord','FileFailure','FileHeaderTrailer','FISFieldStartEndPositions',,'FISFieldStartEndPositions_temp','FISWalletMapping',,'StgReturnFileData',)
,'FISFieldStartEndPositions_bkp_20210914', 'FISFieldStartEndPositions_bkp_20211103_before_TRIM', 'temp_CardBenefitLoad', 'FISWalletMapping_STAGE', 'FISWalletMapping_bkp_20211231_beforeALGN'
*/

select distinct 'select '+ ''''+table_schema+'.'+ table_name +''''+ ' as TableName ' +','+ 'count(*) as RecordCount from ' + table_schema + '.' + table_name + ' Union ' from information_schema.columns 
where TABLE_SCHEMA in ('flex') 

select distinct 'select top 10 '+''''++table_schema+'.'+ table_name +''''+ ' as TableName , * from ' +table_schema+'.'+ table_name from information_schema.columns where TABLE_SCHEMA in ('flex') 


select
'select top 100 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME +''''+ ' as COLUMN_NAME,' 
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' + ' with (nolock) '+
') a union '
from  information_Schema.COLUMNS
where 1=1 and 
TABLE_SCHEMA in ('flex') 
and COLUMN_NAME not in ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')
and DATA_TYPE IN ('float','bigint','bit','datetime','nvarchar','varchar')


-- Record Count
select 'flex.BatchHeaderTrailer' as TableName ,count(*) as RecordCount from flex.BatchHeaderTrailer Union 
select 'flex.DetailRecord' as TableName ,count(*) as RecordCount from flex.DetailRecord Union 
select 'flex.DetailRecord_bkp_20220623_Aetna_COVID' as TableName ,count(*) as RecordCount from flex.DetailRecord_bkp_20220623_Aetna_COVID Union 
select 'flex.FileFailure' as TableName ,count(*) as RecordCount from flex.FileFailure Union 
select 'flex.FileHeaderTrailer' as TableName ,count(*) as RecordCount from flex.FileHeaderTrailer Union 
select 'flex.FISFieldStartEndPositions' as TableName ,count(*) as RecordCount from flex.FISFieldStartEndPositions Union 
select 'flex.FISFieldStartEndPositions_bkp_20210914' as TableName ,count(*) as RecordCount from flex.FISFieldStartEndPositions_bkp_20210914 Union 
select 'flex.FISFieldStartEndPositions_bkp_20211103_before_TRIM' as TableName ,count(*) as RecordCount from flex.FISFieldStartEndPositions_bkp_20211103_before_TRIM Union 
select 'flex.FISFieldStartEndPositions_bkp_20220604_before_DF' as TableName ,count(*) as RecordCount from flex.FISFieldStartEndPositions_bkp_20220604_before_DF Union 
select 'flex.FISFieldStartEndPositions_temp' as TableName ,count(*) as RecordCount from flex.FISFieldStartEndPositions_temp Union 
select 'flex.FISWalletMapping' as TableName ,count(*) as RecordCount from flex.FISWalletMapping Union 
select 'flex.FISWalletMapping_bkp_20211231_beforeALGN' as TableName ,count(*) as RecordCount from flex.FISWalletMapping_bkp_20211231_beforeALGN Union 
--select 'flex.FISWalletMapping_STAGE' as TableName ,count(*) as RecordCount from flex.FISWalletMapping_STAGE Union 
select 'flex.FISWalletMapping_STAGE_bkp_20220428' as TableName ,count(*) as RecordCount from flex.FISWalletMapping_STAGE_bkp_20220428 Union 
select 'flex.FISWallets' as TableName ,count(*) as RecordCount from flex.FISWallets Union 
select 'flex.FlipCards' as TableName ,count(*) as RecordCount from flex.FlipCards Union 
select 'flex.StgReturnFileData' as TableName ,count(*) as RecordCount from flex.StgReturnFileData Union 
select 'flex.temp_CardBenefitLoad' as TableName ,count(*) as RecordCount from flex.temp_CardBenefitLoad

-- Top 10
select top 10 'flex.BatchHeaderTrailer' as TableName , * from flex.BatchHeaderTrailer
select top 10 'flex.DetailRecord' as TableName , * from flex.DetailRecord
--select top 10 'flex.DetailRecord_bkp_20220623_Aetna_COVID' as TableName , * from flex.DetailRecord_bkp_20220623_Aetna_COVID
select top 10 'flex.FileFailure' as TableName , * from flex.FileFailure
select top 10 'flex.FileHeaderTrailer' as TableName , * from flex.FileHeaderTrailer
select top 10 'flex.FISFieldStartEndPositions' as TableName , * from flex.FISFieldStartEndPositions
--select top 10 'flex.FISFieldStartEndPositions_bkp_20210914' as TableName , * from flex.FISFieldStartEndPositions_bkp_20210914
--select top 10 'flex.FISFieldStartEndPositions_bkp_20211103_before_TRIM' as TableName , * from flex.FISFieldStartEndPositions_bkp_20211103_before_TRIM
--select top 10 'flex.FISFieldStartEndPositions_bkp_20220604_before_DF' as TableName , * from flex.FISFieldStartEndPositions_bkp_20220604_before_DF
--select top 10 'flex.FISFieldStartEndPositions_temp' as TableName , * from flex.FISFieldStartEndPositions_temp
select top 10 'flex.FISWalletMapping' as TableName , * from flex.FISWalletMapping
--select top 10 'flex.FISWalletMapping_bkp_20211231_beforeALGN' as TableName , * from flex.FISWalletMapping_bkp_20211231_beforeALGN
--select top 10 'flex.FISWalletMapping_STAGE' as TableName , * from flex.FISWalletMapping_STAGE
--select top 10 'flex.FISWalletMapping_STAGE_bkp_20220428' as TableName , * from flex.FISWalletMapping_STAGE_bkp_20220428
select top 10 'flex.FISWallets' as TableName , * from flex.FISWallets
select top 10 'flex.FlipCards' as TableName , * from flex.FlipCards
select top 10 'flex.StgReturnFileData' as TableName , * from flex.StgReturnFileData
--select top 10 'flex.temp_CardBenefitLoad' as TableName , * from flex.temp_CardBenefitLoad


select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'Id' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Id] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'InsuranceCarrierId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'InsuranceHealthPlanId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanId] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'PurseName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseName] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'PurseSlot' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseSlot] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'DisplayName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DisplayName] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWallets' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from flex.[FISWallets]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'StgReturnFileData' as TABLE_NAME,'StgReturnFileDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StgReturnFileDataID] as nvarchar))),'"') as VALUE from flex.[StgReturnFileData]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'StgReturnFileData' as TABLE_NAME,'FileTrackID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileTrackID] as nvarchar))),'"') as VALUE from flex.[StgReturnFileData]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'StgReturnFileData' as TABLE_NAME,'RecordData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordData] as nvarchar))),'"') as VALUE from flex.[StgReturnFileData]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'FISWalletMapping' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FISWalletMapping] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'FIS_PurseName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseName] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'FIS_PurseSlot' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseSlot] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'NB_WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NB_WalletCode] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'CarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'HealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'LanguageIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'LanguageLOV' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageLOV] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_bkp_20211231_beforeALGN' as TABLE_NAME,'PurseFundCondition' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseFundCondition] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_bkp_20211231_beforeALGN]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20210914' as TABLE_NAME,'FieldName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FieldName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20210914]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20210914' as TABLE_NAME,'DefaultValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultValue] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20210914]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20210914' as TABLE_NAME,'Required' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Required] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20210914]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20210914' as TABLE_NAME,'OTCColumnName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OTCColumnName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20210914]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'FISWalletMapping' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FISWalletMapping] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'FIS_PurseName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseName] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'FIS_PurseSlot' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseSlot] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'NB_WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NB_WalletCode] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'CarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'HealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'LanguageIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'LanguageLOV' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageLOV] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE' as TABLE_NAME,'PurseFundCondition' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseFundCondition] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'FISWalletMapping' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FISWalletMapping] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'FIS_PurseName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseName] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'FIS_PurseSlot' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseSlot] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'NB_WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NB_WalletCode] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'CarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'HealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'LanguageIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'LanguageLOV' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageLOV] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping_STAGE_bkp_20220428' as TABLE_NAME,'PurseFundCondition' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseFundCondition] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping_STAGE_bkp_20220428]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions' as TABLE_NAME,'FieldName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FieldName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions' as TABLE_NAME,'DefaultValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultValue] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions' as TABLE_NAME,'Required' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Required] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions' as TABLE_NAME,'OTCColumnName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OTCColumnName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'FIS_PurseSlot' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseSlot] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'temp_CardBenefitLoad' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from flex.[temp_CardBenefitLoad]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_temp' as TABLE_NAME,'FieldName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FieldName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_temp]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_temp' as TABLE_NAME,'DefaultValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultValue] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_temp]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_temp' as TABLE_NAME,'Required' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Required] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_temp]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_temp' as TABLE_NAME,'OTCColumnName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OTCColumnName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_temp]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20211103_before_TRIM' as TABLE_NAME,'FieldName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FieldName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20211103_before_TRIM]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20211103_before_TRIM' as TABLE_NAME,'DefaultValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultValue] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20211103_before_TRIM]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20211103_before_TRIM' as TABLE_NAME,'Required' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Required] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20211103_before_TRIM]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20211103_before_TRIM' as TABLE_NAME,'OTCColumnName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OTCColumnName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20211103_before_TRIM]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'FISWalletMapping' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FISWalletMapping] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'FIS_PurseName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseName] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'FIS_PurseSlot' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FIS_PurseSlot] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'NB_WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NB_WalletCode] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'CarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'HealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanID] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'LanguageIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'LanguageLOV' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageLOV] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISWalletMapping' as TABLE_NAME,'PurseFundCondition' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseFundCondition] as nvarchar))),'"') as VALUE from flex.[FISWalletMapping]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'DetailRecordID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DetailRecordID] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'BatchHeaderTrailerId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BatchHeaderTrailerId] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'CardBenefitLoadId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadId] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'nhlinkid' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([nhlinkid] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Suffix' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Suffix] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'SSN' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SSN] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingAddr1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddr1] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingAddr2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddr2] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingPostalCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingPostalCode] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingCountryCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountryCode] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'HomeNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomeNumber] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'PAN/Proxy/ClientUniqueID/DirectAccess' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PAN/Proxy/ClientUniqueID/DirectAccess] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Purse' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Purse] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ClientReferenceNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientReferenceNumber] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ApplyDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ApplyDate] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'PromoCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PromoCode] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'AdditionalInfo1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AdditionalInfo1] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'AdditionalInfo2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AdditionalInfo2] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Comment' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Comment] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'SetCardAssigned' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SetCardAssigned] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'LoaduponActivation' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LoaduponActivation] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'TransactionLogID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TransactionLogID] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ProcessingMessage' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessingMessage] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Filler' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'CombinedRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CombinedRecord] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Direction' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Direction] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RefDetailRecordID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefDetailRecordID] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'DOB' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DOB] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MothersMaidenName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MothersMaidenName] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'EmailAddress' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EmailAddress] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'OtherInformation' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OtherInformation] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'FourthLine' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FourthLine] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'NameonCard' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NameonCard] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ClientUniquePersonIdentifier/FISPersonIdentifier' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientUniquePersonIdentifier/FISPersonIdentifier] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Filler_1_31' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler_1_31] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Filler_2_31' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler_2_31] as nvarchar))),'"') as VALUE from flex.[DetailRecord_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'FlipCardID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FlipCardID] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'MemberCardID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberCardID] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'NHMemberID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHMemberID] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'InsuranceCarrierID_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierID_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'InsuranceHealthPlanID_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'ClientID_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'SubProgramID_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'PackageID_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'PurseFundCondition_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseFundCondition_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'LanguageIndicator_old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator_old] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'InsuranceCarrierID_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierID_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'InsuranceHealthPlanID_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'ClientID_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'SubProgramID_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'PackageID_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'PurseFundCondition_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PurseFundCondition_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'LanguageIndicator_new' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator_new] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'IsProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'ErrorNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ErrorNumber] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'ErrorDescription' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ErrorDescription] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'NHLinkid' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkid] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FlipCards' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from flex.[FlipCards]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'FileHeaderTrailerId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileHeaderTrailerId] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'FileTrackID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileTrackID] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'FileDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileDate] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'FileTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileTime] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'CompanyId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CompanyId] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'LogFileIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LogFileIndicator] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'TestProdIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TestProdIndicator] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'Reserved' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Reserved] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'ProcessDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessDate] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'ProcessTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'ClientLookup' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientLookup] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'HeaderFiller1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HeaderFiller1] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'HeaderFiller2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HeaderFiller2] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'TrailerFiller' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TrailerFiller] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'CombinedRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CombinedRecord] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'RefFileHeaderTrailerId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefFileHeaderTrailerId] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'Direction' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Direction] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileHeaderTrailer' as TABLE_NAME,'ErrorCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ErrorCode] as nvarchar))),'"') as VALUE from flex.[FileHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'BatchHeaderTrailerId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BatchHeaderTrailerId] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'FileHeaderTrailerId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileHeaderTrailerId] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'SubprogramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubprogramID] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'CompanyCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CompanyCode] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'SortCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SortCode] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingAddressee' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingAddressee] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingAddress1] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingAddress2] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingCity] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'HeaderFiller1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HeaderFiller1] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingState] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingZip' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingZip] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingAttention' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingAttention] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'UserOnly' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserOnly] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ProxyIndicatorProcessing' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProxyIndicatorProcessing] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'SpecialProcessingIndicators' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SpecialProcessingIndicators] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'BulkShippingPhoneNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BulkShippingPhoneNumber] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'PhoneFormatOverride' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PhoneFormatOverride] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ClientIDExtended' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientIDExtended] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'SubprogramIDExtended' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubprogramIDExtended] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'PackageIDExtended' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageIDExtended] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingAddress1extended' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingAddress1extended] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'ShippingAddress2extended' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShippingAddress2extended] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'PhysicalExpirationinMonths' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PhysicalExpirationinMonths] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'HeaderFiller2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HeaderFiller2] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'OrderID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OrderID] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'TrailerFiller' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TrailerFiller] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'CombinedRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CombinedRecord] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'Direction' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Direction] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'BatchHeaderTrailer' as TABLE_NAME,'RefBatchHeaderTrailerID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefBatchHeaderTrailerID] as nvarchar))),'"') as VALUE from flex.[BatchHeaderTrailer]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'DetailRecordID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DetailRecordID] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'BatchHeaderTrailerId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BatchHeaderTrailerId] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'CardBenefitLoadId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadId] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'nhlinkid' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([nhlinkid] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Suffix' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Suffix] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'SSN' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SSN] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MailingAddr1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddr1] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MailingAddr2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddr2] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MailingPostalCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingPostalCode] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MailingCountryCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountryCode] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'HomeNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomeNumber] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'PAN/Proxy/ClientUniqueID/DirectAccess' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PAN/Proxy/ClientUniqueID/DirectAccess] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Purse' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Purse] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'ClientReferenceNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientReferenceNumber] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'ApplyDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ApplyDate] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'PromoCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PromoCode] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'AdditionalInfo1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AdditionalInfo1] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'AdditionalInfo2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AdditionalInfo2] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Comment' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Comment] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'SetCardAssigned' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SetCardAssigned] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'LoaduponActivation' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LoaduponActivation] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'TransactionLogID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TransactionLogID] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'ProcessingMessage' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessingMessage] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Filler' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'CombinedRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CombinedRecord] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Direction' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Direction] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'RefDetailRecordID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefDetailRecordID] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'DOB' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DOB] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'MothersMaidenName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MothersMaidenName] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'EmailAddress' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EmailAddress] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'OtherInformation' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OtherInformation] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'FourthLine' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FourthLine] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'NameonCard' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NameonCard] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'ClientUniquePersonIdentifier/FISPersonIdentifier' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientUniquePersonIdentifier/FISPersonIdentifier] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Filler_1_31' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler_1_31] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'DetailRecord' as TABLE_NAME,'Filler_2_31' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler_2_31] as nvarchar))),'"') as VALUE from flex.[DetailRecord]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20220604_before_DF' as TABLE_NAME,'FieldName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FieldName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20220604_before_DF]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20220604_before_DF' as TABLE_NAME,'DefaultValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultValue] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20220604_before_DF]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20220604_before_DF' as TABLE_NAME,'Required' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Required] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20220604_before_DF]) a union 
--select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FISFieldStartEndPositions_bkp_20220604_before_DF' as TABLE_NAME,'OTCColumnName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OTCColumnName] as nvarchar))),'"') as VALUE from flex.[FISFieldStartEndPositions_bkp_20220604_before_DF]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'FileFailureID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileFailureID] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'FileTrackID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileTrackID] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'Filler' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Filler] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'ProcessingMessage' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessingMessage] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'CombinedRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CombinedRecord] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'ProcessDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessDate] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'ProcessTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'FileRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileRecordStatusCode] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a union 
select top 100 * from  (select distinct  'flex' as TABLE_SCHEMA,'FileFailure' as TABLE_NAME,'RefFileTrackId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefFileTrackId] as nvarchar))),'"') as VALUE from flex.[FileFailure]) a