select * from information_schema.SCHEMATA order by schema_name
select * from information_schema.TABLES where TABLE_SCHEMA like 'jobs'
select * from information_schema.columns where table_schema = 'jobs'

select
'select top 40 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+'|'    +''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+ '|'     +'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME+ '|'    +''''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' +
') a union '
from  information_Schema.COLUMNS
where table_schema = 'jobs' and table_name not in ('Events_BKP27')
and column_name not in ('CreateDate', 'ModifyDate', 'CreateUser', 'ModifyUser')
and data_type in ('nvarchar','bigint','datetime2','bit','varchar','datetime','int','decimal') --'varbinary' 'uniqueidentifier' removed


select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'PrinterJobHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobHistoryId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'PrinterProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobFilename|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobFilename] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobStatus] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobGroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobGroupName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'StatusDescription|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StatusDescription] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobSettings|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobSettings] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'RequesterUsername|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterUsername] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'RequesterEmail|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterEmail] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PrinterProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileId] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ProfilePasswordHash|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfilePasswordHash] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ProfilePasswordSalt|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfilePasswordSalt] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PrinterDestinationHostname|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterDestinationHostname] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PrinterDestinationIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterDestinationIP] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PCHostname|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PCHostname] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ADAccountName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ADAccountName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'PrinterProfileUserId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileUserId] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'ProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'UserProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'IsAuthorized|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsAuthorized] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'PrinterCallbackId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterCallbackId] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'JobStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobStatus] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'EventTable|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventTable] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'EventData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventData] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobData|' as TABLE_NAME,'PrinterJobDataId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobDataId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobData]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobData|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobData]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobData|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobData]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'CallerDispositionsID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerDispositionsID] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'CallerTypeID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerTypeID] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'DispositionType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DispositionType] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerTypes|' as TABLE_NAME,'CallerTypeID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerTypeID] as nvarchar))),'"') as VALUE from jobs.[CallerTypes]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerTypes|' as TABLE_NAME,'CallerType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerType] as nvarchar))),'"') as VALUE from jobs.[CallerTypes]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerTypes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[CallerTypes]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'PrinterJobGroupId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobGroupId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'GroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([GroupName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'GroupActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([GroupActionCode] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionId] as nvarchar))),'"') as VALUE from jobs.[Actions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionName] as nvarchar))),'"') as VALUE from jobs.[Actions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[Actions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[Actions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'EventActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventActionId] as nvarchar))),'"') as VALUE from jobs.[EventActions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[EventActions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[EventActions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[EventActions]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventId] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'CallBound|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBound] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventName] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventTriggerBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventTriggerBy] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'ParentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentEventId] as nvarchar))),'"') as VALUE from jobs.[Events]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'PageActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'PageActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'IsContinuous|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsContinuous] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ScheduledRunTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScheduledRunTime] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageActionProcessQueueHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionProcessQueueHistoryId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[PageEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[PageEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'ReferenceData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceData] as nvarchar))),'"') as VALUE from jobs.[PageEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from jobs.[PageEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PageEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'InvoicePaymentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'ReferenceData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceData] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'InvoicePaymentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'InvoicePaymentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'InvoicePaymentActionProcessQueueHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentActionProcessQueueHistoryId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'InvoicePaymentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'InvoicePaymentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[pageevents1]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[pageevents1]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'ReferenceData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceData] as nvarchar))),'"') as VALUE from jobs.[pageevents1]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from jobs.[pageevents1]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[pageevents1]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'SheduleConfigurationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SheduleConfigurationId] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'InsuranceCarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'InsuranceHealthPlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanId] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'StartDay|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StartDay] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'EndDay|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndDay] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'StartTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StartTime] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'EndTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndTime] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'JobType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobType] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'ConfigData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ConfigData] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionSchemaData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionSchemaData] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'CallPageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallPageEventId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ParentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'RefType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefType] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionProcessQueueHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueHistoryId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionSchemaData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionSchemaData] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'CallPageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallPageEventId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ParentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'RefType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefType] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'PrinterProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobFilename|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobFilename] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobStatus] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobGroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobGroupName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'StatusDescription|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StatusDescription] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobSettings|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobSettings] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'RequesterUsername|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterUsername] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'RequesterEmail|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterEmail] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'SheduleJobSummaryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SheduleJobSummaryId] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'SheduleConfigurationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SheduleConfigurationId] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'LastRun|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastRun] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'Summary|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Summary] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary]) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary]) a


/*
declare @SearchPredicate nvarchar(50)
set @SearchPredicate = 'Mobile Hearing Aids'
*/

select
'select top 40 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+'|'    +''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+ '|'     +'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME+ '|'    +''''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' + ' where '+ 'ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar)))' + ' like '+ '@SearchPredicate' + 
+ ') a union '
from  information_Schema.COLUMNS
where table_schema = 'jobs' and table_name not in ('Events_BKP27')
and column_name not in ('CreateDate', 'ModifyDate', 'CreateUser', 'ModifyUser')
and data_type in ('nvarchar','bigint','datetime2','bit','varchar','datetime','int','decimal') --'varbinary' 'uniqueidentifier' removed


declare @SearchPredicate nvarchar(50)
set @SearchPredicate = '%Ruskin%'

select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'PrinterJobHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobHistoryId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([PrinterJobHistoryId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([PrinterJobId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'PrinterProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([PrinterProfileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobFilename|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobFilename] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([JobFilename] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobStatus] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([JobStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobGroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobGroupName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([JobGroupName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'StatusDescription|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StatusDescription] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([StatusDescription] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'JobSettings|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobSettings] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([JobSettings] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'RequesterUsername|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterUsername] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([RequesterUsername] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'RequesterEmail|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterEmail] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([RequesterEmail] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobHistory] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PrinterProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileId] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([PrinterProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([ProfileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ProfilePasswordHash|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfilePasswordHash] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([ProfilePasswordHash] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ProfilePasswordSalt|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfilePasswordSalt] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([ProfilePasswordSalt] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PrinterDestinationHostname|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterDestinationHostname] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([PrinterDestinationHostname] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PrinterDestinationIP|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterDestinationIP] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([PrinterDestinationIP] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'PCHostname|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PCHostname] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([PCHostname] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfiles|' as TABLE_NAME,'ADAccountName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ADAccountName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfiles] where ltrim(rtrim(cast([ADAccountName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'PrinterProfileUserId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileUserId] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers] where ltrim(rtrim(cast([PrinterProfileUserId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'ProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers] where ltrim(rtrim(cast([ProfileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'UserProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers] where ltrim(rtrim(cast([UserProfileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'IsAuthorized|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsAuthorized] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers] where ltrim(rtrim(cast([IsAuthorized] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterProfileUsers|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterProfileUsers] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'PrinterCallbackId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterCallbackId] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([PrinterCallbackId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([PrinterJobId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'JobStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobStatus] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([JobStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'EventTable|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventTable] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([EventTable] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'EventData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventData] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([EventData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterCallbacks|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterCallbacks] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobData|' as TABLE_NAME,'PrinterJobDataId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobDataId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobData] where ltrim(rtrim(cast([PrinterJobDataId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobData|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobData] where ltrim(rtrim(cast([PrinterJobId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobData|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobData] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'CallerDispositionsID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerDispositionsID] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions] where ltrim(rtrim(cast([CallerDispositionsID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'CallerTypeID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerTypeID] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions] where ltrim(rtrim(cast([CallerTypeID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'DispositionType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DispositionType] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions] where ltrim(rtrim(cast([DispositionType] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerDispositions|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[CallerDispositions] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerTypes|' as TABLE_NAME,'CallerTypeID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerTypeID] as nvarchar))),'"') as VALUE from jobs.[CallerTypes] where ltrim(rtrim(cast([CallerTypeID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerTypes|' as TABLE_NAME,'CallerType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallerType] as nvarchar))),'"') as VALUE from jobs.[CallerTypes] where ltrim(rtrim(cast([CallerType] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'CallerTypes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[CallerTypes] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'PrinterJobGroupId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobGroupId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups] where ltrim(rtrim(cast([PrinterJobGroupId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'GroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([GroupName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups] where ltrim(rtrim(cast([GroupName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'GroupActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([GroupActionCode] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups] where ltrim(rtrim(cast([GroupActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobGroups|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobGroups] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionId] as nvarchar))),'"') as VALUE from jobs.[Actions] where ltrim(rtrim(cast([ActionId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionName] as nvarchar))),'"') as VALUE from jobs.[Actions] where ltrim(rtrim(cast([ActionName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[Actions] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Actions|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[Actions] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'EventActionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventActionId] as nvarchar))),'"') as VALUE from jobs.[EventActions] where ltrim(rtrim(cast([EventActionId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[EventActions] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[EventActions] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'EventActions|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[EventActions] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventId] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([EventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'CallBound|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallBound] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([CallBound] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventName] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([EventName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'EventTriggerBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventTriggerBy] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([EventTriggerBy] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'Events|' as TABLE_NAME,'ParentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentEventId] as nvarchar))),'"') as VALUE from jobs.[Events] where ltrim(rtrim(cast([ParentEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'PageActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([PageActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'PageActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([PageActionStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([PageEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([ProcessTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'IsContinuous|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsContinuous] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([IsContinuous] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueue|' as TABLE_NAME,'ScheduledRunTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ScheduledRunTime] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueue] where ltrim(rtrim(cast([ScheduledRunTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageActionProcessQueueHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionProcessQueueHistoryId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([PageActionProcessQueueHistoryId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([PageActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageActionStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([PageActionStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([PageEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([ProcessTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageActionProcessQueueHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PageActionProcessQueueHistory] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[PageEvents] where ltrim(rtrim(cast([PageEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[PageEvents] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'ReferenceData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceData] as nvarchar))),'"') as VALUE from jobs.[PageEvents] where ltrim(rtrim(cast([ReferenceData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from jobs.[PageEvents] where ltrim(rtrim(cast([IsProcessed] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PageEvents|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PageEvents] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'InvoicePaymentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents] where ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'ReferenceData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceData] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents] where ltrim(rtrim(cast([ReferenceData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentEvents|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentEvents] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'InvoicePaymentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue] where ltrim(rtrim(cast([InvoicePaymentActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'InvoicePaymentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue] where ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue] where ltrim(rtrim(cast([ProcessTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueue] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'InvoicePaymentActionProcessQueueHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentActionProcessQueueHistoryId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([InvoicePaymentActionProcessQueueHistoryId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'InvoicePaymentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([InvoicePaymentActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'InvoicePaymentEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([InvoicePaymentEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([ProcessTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'InvoicePaymentActionProcessQueueHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[InvoicePaymentActionProcessQueueHistory] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'PageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PageEventId] as nvarchar))),'"') as VALUE from jobs.[pageevents1] where ltrim(rtrim(cast([PageEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'EventCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EventCode] as nvarchar))),'"') as VALUE from jobs.[pageevents1] where ltrim(rtrim(cast([EventCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'ReferenceData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ReferenceData] as nvarchar))),'"') as VALUE from jobs.[pageevents1] where ltrim(rtrim(cast([ReferenceData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'IsProcessed|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsProcessed] as nvarchar))),'"') as VALUE from jobs.[pageevents1] where ltrim(rtrim(cast([IsProcessed] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'pageevents1|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[pageevents1] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'SheduleConfigurationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SheduleConfigurationId] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([SheduleConfigurationId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'InsuranceCarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'InsuranceHealthPlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanId] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([InsuranceHealthPlanId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'StartDay|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StartDay] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([StartDay] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'EndDay|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndDay] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([EndDay] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'StartTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StartTime] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([StartTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'EndTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EndTime] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([EndTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'JobType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobType] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([JobType] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'ConfigData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ConfigData] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([ConfigData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleConfiguration|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[SheduleConfiguration] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionSchemaData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionSchemaData] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ActionSchemaData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ActionStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'CallPageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallPageEventId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([CallPageEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ParentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ParentActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([ProcessTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueues|' as TABLE_NAME,'RefType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefType] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueues] where ltrim(rtrim(cast([RefType] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionProcessQueueHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueHistoryId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ActionProcessQueueHistoryId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionSchemaData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionSchemaData] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ActionSchemaData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ActionStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ActionCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActionCode] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ActionCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'CallPageEventId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CallPageEventId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([CallPageEventId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ParentActionProcessQueueId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentActionProcessQueueId] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ParentActionProcessQueueId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ProcessStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessStatus] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ProcessStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'ProcessTime|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProcessTime] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([ProcessTime] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'ActionProcessQueuesHistory|' as TABLE_NAME,'RefType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefType] as nvarchar))),'"') as VALUE from jobs.[ActionProcessQueuesHistory] where ltrim(rtrim(cast([RefType] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'PrinterJobId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterJobId] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([PrinterJobId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'PrinterProfileName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrinterProfileName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([PrinterProfileName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobFilename|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobFilename] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([JobFilename] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobStatus|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobStatus] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([JobStatus] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobGroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobGroupName] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([JobGroupName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'StatusDescription|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StatusDescription] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([StatusDescription] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'JobSettings|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([JobSettings] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([JobSettings] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'RequesterUsername|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterUsername] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([RequesterUsername] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'RequesterEmail|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequesterEmail] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([RequesterEmail] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'PrinterJobQueue|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[PrinterJobQueue] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'SheduleJobSummaryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SheduleJobSummaryId] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary] where ltrim(rtrim(cast([SheduleJobSummaryId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'SheduleConfigurationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SheduleConfigurationId] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary] where ltrim(rtrim(cast([SheduleConfigurationId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'LastRun|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastRun] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary] where ltrim(rtrim(cast([LastRun] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'Summary|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Summary] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary] where ltrim(rtrim(cast([Summary] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'jobs|' as TABLE_SCHEMA,'SheduleJobSummary|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from jobs.[SheduleJobSummary] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a