select * from information_schema.columns where table_schema like '%otcfunds%'

select distinct table_name from information_schema.columns where TABLE_SCHEMA in ('otcfunds')
select distinct ''''+table_name+''''+ ',' from information_schema.columns where TABLE_SCHEMA in ('otcfunds')

select * from information_schema.columns where table_schema = 'otcfunds'

/*
('CardBenefitLoad','CardBenefitLoad_Error','ClientBenefitRulesData','FileInfo','FileTrack','FTPUserInfo','PeriodFrequencyMapping')
*/

select distinct 'select '+ ''''+table_schema+'.'+ table_name +''''+ ' as TableName ' +','+ 'count(*) as RecordCount from ' + table_schema + '.' + table_name + ' Union ' from information_schema.columns 
where TABLE_SCHEMA in ('otcfunds') 

select 'otcfunds.BenefitCardMapping' as TableName ,count(*) as RecordCount from otcfunds.BenefitCardMapping Union 
select 'otcfunds.CardBenefitLoad_CI' as TableName ,count(*) as RecordCount from otcfunds.CardBenefitLoad_CI Union 
select 'otcfunds.CardBenefitLoad_CI_BANCORP' as TableName ,count(*) as RecordCount from otcfunds.CardBenefitLoad_CI_BANCORP Union 
select 'otcfunds.CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TableName ,count(*) as RecordCount from otcfunds.CardBenefitLoad_CI_bkp_20220623_Aetna_COVID Union 
select 'otcfunds.CardBenefitLoad_CI_bkp_20220811' as TableName ,count(*) as RecordCount from otcfunds.CardBenefitLoad_CI_bkp_20220811 Union 
select 'otcfunds.CardBenefitLoad_Error' as TableName ,count(*) as RecordCount from otcfunds.CardBenefitLoad_Error Union 
select 'otcfunds.CardBenefitLoad_FD' as TableName ,count(*) as RecordCount from otcfunds.CardBenefitLoad_FD Union 
select 'otcfunds.ClientBenefitRulesData' as TableName ,count(*) as RecordCount from otcfunds.ClientBenefitRulesData Union 
select 'otcfunds.FileInfo' as TableName ,count(*) as RecordCount from otcfunds.FileInfo Union 
select 'otcfunds.FileTrack' as TableName ,count(*) as RecordCount from otcfunds.FileTrack Union 
select 'otcfunds.FTPUserInfo' as TableName ,count(*) as RecordCount from otcfunds.FTPUserInfo Union 
select 'otcfunds.MemberAddressChange' as TableName ,count(*) as RecordCount from otcfunds.MemberAddressChange Union 
select 'otcfunds.PeriodFrequencyMapping' as TableName ,count(*) as RecordCount from otcfunds.PeriodFrequencyMapping


select distinct 'select top 10 '+''''++table_schema+'.'+ table_name +''''+ ' as TableName , * from ' +table_schema+'.'+ table_name from information_schema.columns where TABLE_SCHEMA in ('otcfunds') 

select top 10 'otcfunds.BenefitCardMapping' as TableName , * from otcfunds.BenefitCardMapping
select top 10 'otcfunds.CardBenefitLoad_CI' as TableName , * from otcfunds.CardBenefitLoad_CI
--select top 10 'otcfunds.CardBenefitLoad_CI_BANCORP' as TableName , * from otcfunds.CardBenefitLoad_CI_BANCORP
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20220623_Aetna_COVID
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20220811' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20220811
select top 10 'otcfunds.CardBenefitLoad_Error' as TableName , * from otcfunds.CardBenefitLoad_Error
select top 10 'otcfunds.CardBenefitLoad_FD' as TableName , * from otcfunds.CardBenefitLoad_FD
select top 10 'otcfunds.ClientBenefitRulesData' as TableName , * from otcfunds.ClientBenefitRulesData
--select top 10 'otcfunds.FileInfo' as TableName , * from otcfunds.FileInfo
--select top 10 'otcfunds.FileTrack' as TableName , * from otcfunds.FileTrack
--select top 10 'otcfunds.FTPUserInfo' as TableName , * from otcfunds.FTPUserInfo
select top 10 'otcfunds.MemberAddressChange' as TableName , * from otcfunds.MemberAddressChange
select top 10 'otcfunds.PeriodFrequencyMapping' as TableName , * from otcfunds.PeriodFrequencyMapping


select top 10 'otcfunds.BenefitCardMapping' as TableName , * from otcfunds.BenefitCardMapping
--select top 10 'otcfunds.BenefitCardMapping_bkp_20230107_before_EH_43K_ReIssue' as TableName , * from otcfunds.BenefitCardMapping_bkp_20230107_before_EH_43K_ReIssue
--select top 10 'otcfunds.BenefitCardMapping_bkp_20230118_beforeCHC_NHLinkID' as TableName , * from otcfunds.BenefitCardMapping_bkp_20230118_beforeCHC_NHLinkID
--select top 10 'otcfunds.BenefitCardMapping_bkp_20230125_MP_Ignore' as TableName , * from otcfunds.BenefitCardMapping_bkp_20230125_MP_Ignore
--select top 10 'otcfunds.CardBenefitLoad_bkp_20220227_before_FDRefactor' as TableName , * from otcfunds.CardBenefitLoad_bkp_20220227_before_FDRefactor
select top 10 'otcfunds.CardBenefitLoad_CI' as TableName , * from otcfunds.CardBenefitLoad_CI
--select top 10 'otcfunds.CardBenefitLoad_CI_Algn_DUP_20230205' as TableName , * from otcfunds.CardBenefitLoad_CI_Algn_DUP_20230205
--select top 10 'otcfunds.CardBenefitLoad_CI_BANCORP_temp' as TableName , * from otcfunds.CardBenefitLoad_CI_BANCORP_temp
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20220623_Aetna_COVID
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20220811' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20220811
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20221126' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20221126
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20230105_before_EH_Dups' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20230105_before_EH_Dups
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20230107_before_EH_43K_ReIssue' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20230107_before_EH_43K_ReIssue
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20230118_beforeCHC_NHLinkID' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20230118_beforeCHC_NHLinkID
--select top 10 'otcfunds.CardBenefitLoad_CI_bkp_20230125_MP_Ignore' as TableName , * from otcfunds.CardBenefitLoad_CI_bkp_20230125_MP_Ignore
select top 10 'otcfunds.CardBenefitLoad_CI_TESTCARDS' as TableName , * from otcfunds.CardBenefitLoad_CI_TESTCARDS
select top 10 'otcfunds.CardBenefitLoad_Error' as TableName , * from otcfunds.CardBenefitLoad_Error
select top 10 'otcfunds.CardBenefitLoad_FD' as TableName , * from otcfunds.CardBenefitLoad_FD
--select top 10 'otcfunds.CardBenefitLoad_FD_BANCORP_temp' as TableName , * from otcfunds.CardBenefitLoad_FD_BANCORP_temp
--select top 10 'otcfunds.CardBenefitLoad_FD_bkp_ElevanceBad' as TableName , * from otcfunds.CardBenefitLoad_FD_bkp_ElevanceBad
--select top 10 'otcfunds.CardBenefitLoad_FD_bkp_ElevanceGood' as TableName , * from otcfunds.CardBenefitLoad_FD_bkp_ElevanceGood
select top 10 'otcfunds.ClientBenefitRulesData' as TableName , * from otcfunds.ClientBenefitRulesData
select top 10 'otcfunds.FileInfo' as TableName , * from otcfunds.FileInfo
select top 10 'otcfunds.FileInfo_20221219' as TableName , * from otcfunds.FileInfo_20221219
select top 10 'otcfunds.FileTrack' as TableName , * from otcfunds.FileTrack
select top 10 'otcfunds.FTPUserInfo' as TableName , * from otcfunds.FTPUserInfo
select top 10 'otcfunds.MemberAddressChange' as TableName , * from otcfunds.MemberAddressChange
select top 10 'otcfunds.PeriodFrequencyMapping' as TableName , * from otcfunds.PeriodFrequencyMapping
select top 10 'otcfunds.RewardClientCodeMapping' as TableName , * from otcfunds.RewardClientCodeMapping


select
'select top 100 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME +''''+ ' as COLUMN_NAME,' 
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' +
') a union '
from  information_Schema.COLUMNS
where 1=1 and 
TABLE_SCHEMA in ('otcfunds')  
and COLUMN_NAME not in ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')
and DATA_TYPE IN ('float','bigint','bit','datetime','nvarchar','varchar')


select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'RequestRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'RequestProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'RequestProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'ResponseRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'ResponseRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatusCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'ResponseProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'ResponseProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'FirstTimeCardIssued' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstTimeCardIssued] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'RefCardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefCardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_FD' as TABLE_NAME,'MemberDataSourceFile' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSourceFile] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_FD]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'ID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ID] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'ClientName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientName] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'DataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DataSource] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'InsuranceCarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierID] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'InsuranceHealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'BenefitCategory' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCategory] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'BenefitBehaviour' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitBehaviour] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'BenefitFrequencyType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyType] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'BenefitForType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitForType] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'BenefitValueSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitValueSource] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'isActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([isActive] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'IsCardIssuance' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsCardIssuance] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'ClientBenefitRulesData' as TABLE_NAME,'LanguageIndicator' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LanguageIndicator] as nvarchar))),'"') as VALUE from otcfunds.[ClientBenefitRulesData]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'PeriodFrequencyMapping' as TABLE_NAME,'PeriodName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PeriodName] as nvarchar))),'"') as VALUE from otcfunds.[PeriodFrequencyMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'RequestRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'RequestProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'RequestProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'ResponseRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'ResponseRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatusCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'ResponseProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'ResponseProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'FirstTimeCardIssued' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstTimeCardIssued] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'RefCardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefCardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220811' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220811]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FileInfoID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileInfoID] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'Direction' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Direction] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FileName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileName] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FileExtension' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileExtension] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FileFormat' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileFormat] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FileType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileType] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'SnapshotFlag' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SnapshotFlag] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'Frequency' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Frequency] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'PickDropTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PickDropTime] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FromLocation' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FromLocation] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'ToLocation' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ToLocation] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'DataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DataSource] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'isActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([isActive] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsHeaderRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsHeaderRecord] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'FileFormatValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileFormatValue] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsTrailerRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsTrailerRecord] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'isAckFileToFTP' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([isAckFileToFTP] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsDelFileFromClientFTP' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsDelFileFromClientFTP] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsControlFile' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsControlFile] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsPGP' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsPGP] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'PGPFileExtension' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PGPFileExtension] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'PGPKeyName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PGPKeyName] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsFileHeaderRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsFileHeaderRecord] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsFileTrailerRecord' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsFileTrailerRecord] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'MasterDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MasterDataSource] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'IsThresholdCheck' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsThresholdCheck] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'ThresholdValue' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ThresholdValue] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'isOutFileEmail' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([isOutFileEmail] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'OutFileEmail' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OutFileEmail] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'RecordTypes' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordTypes] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileInfo' as TABLE_NAME,'Level1ClientId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Level1ClientId] as nvarchar))),'"') as VALUE from otcfunds.[FileInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_Error' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_Error]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MemberAddressChangeID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberAddressChangeID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'CardBenefitLoadId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadId] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'CardNumberProxy' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardNumberProxy] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingAddress1_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingAddress2_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingCity_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingState_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingZipCode_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingCountry_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'HomePhoneNbr_Old' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr_Old] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingAddress1_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingAddress2_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingCity_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingState_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingZipCode_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'MailingCountry_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'HomePhoneNbr_New' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr_New] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'RequestRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'RequestProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'RequestProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ResponseRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ResponseRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatusCode] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ResponseProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ResponseProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'RefMemberAddressChangeID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefMemberAddressChangeID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'MemberAddressChange' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from otcfunds.[MemberAddressChange]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'FtpID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FtpID] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'HostAddress' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HostAddress] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'Port' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Port] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'UserID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserID] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'Password' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Password] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'WinSCPLoginName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WinSCPLoginName] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'ContactPerson' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ContactPerson] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'ContactPhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ContactPhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'ContactEmail' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ContactEmail] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'isActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([isActive] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'FileType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileType] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'SnapshotFlag' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SnapshotFlag] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FTPUserInfo' as TABLE_NAME,'Direction' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Direction] as nvarchar))),'"') as VALUE from otcfunds.[FTPUserInfo]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'RequestRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'RequestProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'RequestProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ResponseRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ResponseRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatusCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ResponseProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ResponseProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'FirstTimeCardIssued' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstTimeCardIssued] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'RefCardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefCardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'DiscretionaryData1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DiscretionaryData1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'FourthLine' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FourthLine] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'CarrierMessage' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierMessage] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'ProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProgramID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'FileGenInd' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileGenInd] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'Level1ClientId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Level1ClientId] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI' as TABLE_NAME,'BenefitCardMappingID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardMappingID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'BenefitCardMappingID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardMappingID] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'mstrEligID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([mstrEligID] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'Level1ClientId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Level1ClientId] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'DataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DataSource] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'BenefitCardMapping' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[BenefitCardMapping]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'FileTrackID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileTrackID] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'FileInfoID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileInfoID] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'DirectionCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DirectionCode] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'FileName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileName] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'FileFormat' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileFormat] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'FileType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FileType] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'DataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DataSource] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'DateReceived' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DateReceived] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'DateProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DateProcessed] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'TotalRecords' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TotalRecords] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'RecordsProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordsProcessed] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'RecordsErrored' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordsErrored] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'LoadStartTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LoadStartTime] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'LoadEndTime' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LoadEndTime] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'StatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([StatusCode] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'RefFileTrackID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefFileTrackID] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'FileTrack' as TABLE_NAME,'SnapshotFlag' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SnapshotFlag] as nvarchar))),'"') as VALUE from otcfunds.[FileTrack]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RequestRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RequestProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RequestProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ResponseRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ResponseRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatusCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ResponseProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'ResponseProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'FirstTimeCardIssued' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstTimeCardIssued] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'RefCardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefCardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_bkp_20220623_Aetna_COVID' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_bkp_20220623_Aetna_COVID]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'CardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MemberDataID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'ClientCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'NHLinkID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NHLinkID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'RecordType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RecordType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MemberDataSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MemberDataSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'BenefitCardNumber' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCardNumber] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'LastName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MiddleInitial' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleInitial] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'FirstName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MailingAddress1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MailingAddress2' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingAddress2] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MailingCity' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCity] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MailingState' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingState] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MailingZipCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingZipCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'MailingCountry' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MailingCountry] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'HomePhoneNbr' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HomePhoneNbr] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'BenefitType' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitType] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'BenefitSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitSource] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'NBWalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NBWalletCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'RequestRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'RequestToBeProcessed' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestToBeProcessed] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'RequestProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'RequestProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RequestProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'ResponseRecordStatus' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatus] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'ResponseRecordStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseRecordStatusCode] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'ResponseProcessedFileID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedFileID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'ResponseProcessedDate' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ResponseProcessedDate] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'FirstTimeCardIssued' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstTimeCardIssued] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'RefCardBenefitLoadID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RefCardBenefitLoadID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'Language' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Language] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'DiscretionaryData1' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DiscretionaryData1] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'FourthLine' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FourthLine] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'CarrierMessage' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierMessage] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'Level1ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Level1ClientID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'ClientID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ClientID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'SubProgramID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SubProgramID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a union 
select top 100 * from  (select distinct  'otcfunds' as TABLE_SCHEMA,'CardBenefitLoad_CI_BANCORP' as TABLE_NAME,'PackageID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PackageID] as nvarchar))),'"') as VALUE from otcfunds.[CardBenefitLoad_CI_BANCORP]) a 