select * from master.members where datasource = 'ELIG_CAPBC'
select * from orders.orders where NHMemberID in (select NhMemberID from master.members where datasource = 'ELIG_CAPBC') and MemberData like '%2529%'

select * from information_schema.columns where table_schema = 'rulesengine'


declare @SearchPredicate nvarchar(50)
--set @SearchPredicate = '11114'
set @SearchPredicate = '7200'


select
'select top 40 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+'|'    +''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+ '|'     +'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME+ '|'    +''''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' + ' where '+ 'ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar)))' + ' like '+ '@SearchPredicate' + 
+ ') a union '
from  information_Schema.COLUMNS
where TABLE_SCHEMA in ('rulesengine')
--and table_name in ('ApplicationFeatures','AppModuleRoleMenus','AppModuleRoleMenuSubMenuFeatures','AppModuleRoleMenuSubmenus','AppModuleRoles','AppModules','ParentApplicationFeatures','ProviderFeatures','ProviderUserFeatures','SecretQuestions','UserEmails','UserGroupModuleRoles','UserGroupModules','UserGroups','UserPhoneNumbers','UserProfileGroups','UserProfiles','UserProfileSecretAnswers','UserProfileSettings')
and COLUMN_NAME not in ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')
order by table_schema, table_name



select
'select top 100 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+'|'    +''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+ '|'     +'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME+ '|'    +''''+ ' as COLUMN_NAME,'
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' +
') a union '
from  information_Schema.COLUMNS
where TABLE_SCHEMA in ('rulesengine')
and COLUMN_NAME not in ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')
--and TABLE_NAME in ('ApplicationFeatures','AppModuleRoleMenus','AppModuleRoleMenuSubMenuFeatures','AppModuleRoleMenuSubmenus','AppModuleRoles','AppModules','ParentApplicationFeatures','ProviderFeatures','ProviderUserFeatures','SecretQuestions','UserEmails','UserGroupModuleRoles','UserGroupModules','UserGroups','UserPhoneNumbers','UserProfileGroups','UserProfiles','UserProfileSecretAnswers','UserProfileSettings')
order by table_schema, table_name


select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'BenefitCodeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCodeId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'BenefitRuleCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleCode] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'DefaultDisplayName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultDisplayName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'RuleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RuleName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'RuleOptions|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RuleOptions] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'RuleType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RuleType] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRules|' as TABLE_NAME,'BenefitRuleID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleID] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRules]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRules|' as TABLE_NAME,'BenefitRuleText|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleText] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRules]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRules|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRules]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'BenefitRuleData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleData] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'BenefitRuleDataId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleDataId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleData] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleDataHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleDataHistoryId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleDataId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleDataId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENBEHV|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENBEHV] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENCAT|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCAT] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENCATVALUE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCATVALUE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BenefitFrequencyYearsBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENFORTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFORTYPE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENFREQMONTHS|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENFREQTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENTYPE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENVALUESRC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENVALUESRC] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'CarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'CarrierName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'HealthPlanContractId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'HealthPlanNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'PlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'PlanName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENBEHV|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENBEHV] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENCAT|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCAT] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENCATVALUE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCATVALUE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BenefitFrequencyYearsBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENFORTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFORTYPE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENFREQMONTHS|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENFREQTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENTYPE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENVALUESRC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENVALUESRC] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'CarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'CarrierName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierName] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'HealthPlanContractId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'HealthPlanNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'PlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'PlanName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanName] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENBEHV|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENBEHV] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENCAT|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCAT] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENCATVALUE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCATVALUE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BenefitFrequencyYearsBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENFORTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFORTYPE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENFREQMONTHS|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENFREQTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENTYPE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENVALUESRC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENVALUESRC] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'CarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'CarrierName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierName] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'HealthPlanContractId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'HealthPlanNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'PlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a union 
select top 100 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'PlanName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanName] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData]) a




declare @SearchPredicate nvarchar(50)
--set @SearchPredicate = '11114'
set @SearchPredicate = '%BENTYPE%'


select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'BenefitCodeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitCodeId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([BenefitCodeId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'BenefitRuleCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleCode] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([BenefitRuleCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'DefaultDisplayName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultDisplayName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([DefaultDisplayName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'RuleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RuleName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([RuleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'RuleOptions|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RuleOptions] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([RuleOptions] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitCodes|' as TABLE_NAME,'RuleType|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([RuleType] as nvarchar))),'"') as VALUE from rulesengine.[BenefitCodes] where ltrim(rtrim(cast([RuleType] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRules|' as TABLE_NAME,'BenefitRuleID|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleID] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRules] where ltrim(rtrim(cast([BenefitRuleID] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRules|' as TABLE_NAME,'BenefitRuleText|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleText] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRules] where ltrim(rtrim(cast([BenefitRuleText] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRules|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRules] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'BenefitRuleData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleData] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData] where ltrim(rtrim(cast([BenefitRuleData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'BenefitRuleDataId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleDataId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData] where ltrim(rtrim(cast([BenefitRuleDataId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData] where ltrim(rtrim(cast([BenefitRuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesData|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesData] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleData|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleData] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory] where ltrim(rtrim(cast([BenefitRuleData] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleDataHistoryId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleDataHistoryId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory] where ltrim(rtrim(cast([BenefitRuleDataHistoryId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleDataId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleDataId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory] where ltrim(rtrim(cast([BenefitRuleDataId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory] where ltrim(rtrim(cast([BenefitRuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesHistory|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesHistory] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENBEHV|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENBEHV] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENBEHV] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENCAT|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCAT] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENCAT] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENCATVALUE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCATVALUE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENCATVALUE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BenefitFrequencyYearsBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BenefitRuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENFORTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFORTYPE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENFORTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENFREQMONTHS|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENFREQTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENTYPE] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'BENVALUESRC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENVALUESRC] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([BENVALUESRC] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'CarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([CarrierId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'CarrierName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([CarrierName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'HealthPlanContractId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'HealthPlanNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'PlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanId] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([PlanId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'BenefitRulesTempData|' as TABLE_NAME,'PlanName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanName] as nvarchar))),'"') as VALUE from rulesengine.[BenefitRulesTempData] where ltrim(rtrim(cast([PlanName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENBEHV|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENBEHV] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENBEHV] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENCAT|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCAT] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENCAT] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENCATVALUE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCATVALUE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENCATVALUE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BenefitFrequencyYearsBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BenefitRuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENFORTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFORTYPE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENFORTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENFREQMONTHS|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENFREQTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENTYPE] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'BENVALUESRC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENVALUESRC] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([BENVALUESRC] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'CarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([CarrierId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'CarrierName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierName] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([CarrierName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'HealthPlanContractId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'HealthPlanNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'PlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanId] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([PlanId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'HABenefitRulesTempData|' as TABLE_NAME,'PlanName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanName] as nvarchar))),'"') as VALUE from rulesengine.[HABenefitRulesTempData] where ltrim(rtrim(cast([PlanName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENBEHV|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENBEHV] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENBEHV] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENCAT|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCAT] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENCAT] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENCATVALUE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENCATVALUE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENCATVALUE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BenefitFrequencyYearsBy|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BenefitFrequencyYearsBy] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BenefitRuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BenefitRuleId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BenefitRuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENFORTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFORTYPE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENFORTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENFREQMONTHS|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENFREQMONTHS] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENFREQTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENFREQTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENTYPE|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENTYPE] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENTYPE] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'BENVALUESRC|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([BENVALUESRC] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([BENVALUESRC] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'CarrierId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([CarrierId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'CarrierName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CarrierName] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([CarrierName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'HealthPlanContractId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([HealthPlanContractId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'HealthPlanNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([HealthPlanNumber] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'PlanId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanId] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([PlanId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'rulesengine|' as TABLE_SCHEMA,'OTCBenefitRulesTempData|' as TABLE_NAME,'PlanName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanName] as nvarchar))),'"') as VALUE from rulesengine.[OTCBenefitRulesTempData] where ltrim(rtrim(cast([PlanName] as nvarchar))) like @SearchPredicate) a





