select * from auth.UserProfiles where providerCode = 180450
select * from auth.UserProfiles where FirstName  = 'Santhosh'

update auth.UserProfiles set Designation = 'PCC' where UserProfileID = 12913
update auth.UserProfiles set ProviderCode = 180450 where UserProfileID = 12913

declare @SearchPredicate nvarchar(50)
--set @SearchPredicate = '11114'
set @SearchPredicate = '7200'

--Search Predicate Query
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'AppFeatureId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppFeatureId] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([AppFeatureId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'ParentFeatureId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentFeatureId] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([ParentFeatureId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'FeatureSectionName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FeatureSectionName] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([FeatureSectionName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'FeatureName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FeatureName] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([FeatureName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'FeatureCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FeatureCode] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([FeatureCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsDefault|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsDefault] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsDefault] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsSystemFeature|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsSystemFeature] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsSystemFeature] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsCreate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsCreate] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsCreate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsRead|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsRead] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsRead] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsUpdate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsUpdate] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsUpdate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsDelete|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsDelete] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsDelete] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ApplicationFeatures|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[ApplicationFeatures] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenus|' as TABLE_NAME,'AppModuleRoleMenuId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenus] where ltrim(rtrim(cast([AppModuleRoleMenuId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenus|' as TABLE_NAME,'AppModuleRoleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenus] where ltrim(rtrim(cast([AppModuleRoleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenus|' as TABLE_NAME,'AppModuleRoleMenuIconImage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuIconImage] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenus] where ltrim(rtrim(cast([AppModuleRoleMenuIconImage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenus|' as TABLE_NAME,'AppModuleRoleMenuName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuName] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenus] where ltrim(rtrim(cast([AppModuleRoleMenuName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenus|' as TABLE_NAME,'AppModuleRoleMenuPage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuPage] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenus] where ltrim(rtrim(cast([AppModuleRoleMenuPage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenus|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenus] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubMenuFeatures|' as TABLE_NAME,'AppModuleRoleMenuId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubMenuFeatures] where ltrim(rtrim(cast([AppModuleRoleMenuId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubMenuFeatures|' as TABLE_NAME,'AppModuleRoleMenuSubMenuId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuSubMenuId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubMenuFeatures] where ltrim(rtrim(cast([AppModuleRoleMenuSubMenuId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubMenuFeatures|' as TABLE_NAME,'AppFeatureCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppFeatureCode] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubMenuFeatures] where ltrim(rtrim(cast([AppFeatureCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'AppModuleRoleMenuSubmenuId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuSubmenuId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([AppModuleRoleMenuSubmenuId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'AppModuleRoleMenuId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([AppModuleRoleMenuId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'AppModuleRoleMenuSubmenuIconImage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuSubmenuIconImage] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([AppModuleRoleMenuSubmenuIconImage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'AppModuleRoleMenuSubmenuId1|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuSubmenuId1] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([AppModuleRoleMenuSubmenuId1] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'AppModuleRoleMenuSubmenuName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuSubmenuName] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([AppModuleRoleMenuSubmenuName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'AppModuleRoleMenuSubmenuPage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleMenuSubmenuPage] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([AppModuleRoleMenuSubmenuPage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoleMenuSubmenus|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[AppModuleRoleMenuSubmenus] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoles|' as TABLE_NAME,'AppModuleRoleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoles] where ltrim(rtrim(cast([AppModuleRoleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoles|' as TABLE_NAME,'AppModuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleId] as nvarchar))),'"') as VALUE from auth.[AppModuleRoles] where ltrim(rtrim(cast([AppModuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoles|' as TABLE_NAME,'AppModuleRoleIconImage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleIconImage] as nvarchar))),'"') as VALUE from auth.[AppModuleRoles] where ltrim(rtrim(cast([AppModuleRoleIconImage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoles|' as TABLE_NAME,'AppModuleRoleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleName] as nvarchar))),'"') as VALUE from auth.[AppModuleRoles] where ltrim(rtrim(cast([AppModuleRoleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoles|' as TABLE_NAME,'HelpText|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HelpText] as nvarchar))),'"') as VALUE from auth.[AppModuleRoles] where ltrim(rtrim(cast([HelpText] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModuleRoles|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[AppModuleRoles] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModules|' as TABLE_NAME,'AppModuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleId] as nvarchar))),'"') as VALUE from auth.[AppModules] where ltrim(rtrim(cast([AppModuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModules|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[AppModules] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModules|' as TABLE_NAME,'ModuleDomain|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ModuleDomain] as nvarchar))),'"') as VALUE from auth.[AppModules] where ltrim(rtrim(cast([ModuleDomain] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModules|' as TABLE_NAME,'ModuleIconImage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ModuleIconImage] as nvarchar))),'"') as VALUE from auth.[AppModules] where ltrim(rtrim(cast([ModuleIconImage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'AppModules|' as TABLE_NAME,'ModuleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ModuleName] as nvarchar))),'"') as VALUE from auth.[AppModules] where ltrim(rtrim(cast([ModuleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'ParentFeatureId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentFeatureId] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([ParentFeatureId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'ParentFeatureSectionName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentFeatureSectionName] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([ParentFeatureSectionName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'ParentFeatureName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentFeatureName] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([ParentFeatureName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'ParentFeatureCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ParentFeatureCode] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([ParentFeatureCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'OwnerDefault|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OwnerDefault] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([OwnerDefault] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'HCPDefault|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HCPDefault] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([HCPDefault] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'UserDefault|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserDefault] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([UserDefault] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ParentApplicationFeatures|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[ParentApplicationFeatures] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderFeatures|' as TABLE_NAME,'ProviderFeatureId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderFeatureId] as nvarchar))),'"') as VALUE from auth.[ProviderFeatures] where ltrim(rtrim(cast([ProviderFeatureId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderFeatures|' as TABLE_NAME,'AppFeatureCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppFeatureCode] as nvarchar))),'"') as VALUE from auth.[ProviderFeatures] where ltrim(rtrim(cast([AppFeatureCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderFeatures|' as TABLE_NAME,'ProviderId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderId] as nvarchar))),'"') as VALUE from auth.[ProviderFeatures] where ltrim(rtrim(cast([ProviderId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderFeatures|' as TABLE_NAME,'IsExclude|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsExclude] as nvarchar))),'"') as VALUE from auth.[ProviderFeatures] where ltrim(rtrim(cast([IsExclude] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderFeatures|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[ProviderFeatures] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'ProviderUserFeatureId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderUserFeatureId] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([ProviderUserFeatureId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'ProviderId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderId] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([ProviderId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'AppFeatureCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppFeatureCode] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([AppFeatureCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'IsCreate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsCreate] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([IsCreate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'IsRead|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsRead] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([IsRead] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'IsUpdate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsUpdate] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([IsUpdate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'IsDelete|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsDelete] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([IsDelete] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'ProviderUserFeatures|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[ProviderUserFeatures] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'SecretQuestions|' as TABLE_NAME,'SecretQuestionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SecretQuestionId] as nvarchar))),'"') as VALUE from auth.[SecretQuestions] where ltrim(rtrim(cast([SecretQuestionId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'SecretQuestions|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[SecretQuestions] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'SecretQuestions|' as TABLE_NAME,'IsEnabled|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsEnabled] as nvarchar))),'"') as VALUE from auth.[SecretQuestions] where ltrim(rtrim(cast([IsEnabled] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'SecretQuestions|' as TABLE_NAME,'SecretQuestionName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SecretQuestionName] as nvarchar))),'"') as VALUE from auth.[SecretQuestions] where ltrim(rtrim(cast([SecretQuestionName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'SecretQuestions|' as TABLE_NAME,'Set|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Set] as nvarchar))),'"') as VALUE from auth.[SecretQuestions] where ltrim(rtrim(cast([Set] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'UserEmailId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserEmailId] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([UserEmailId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'EmailAddress|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EmailAddress] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([EmailAddress] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'EmailTypeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([EmailTypeId] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([EmailTypeId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'IsEnabled|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsEnabled] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([IsEnabled] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'IsVerified|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsVerified] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([IsVerified] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserEmails|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[UserEmails] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModuleRoles|' as TABLE_NAME,'UserGroupModuleRoleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupModuleRoleId] as nvarchar))),'"') as VALUE from auth.[UserGroupModuleRoles] where ltrim(rtrim(cast([UserGroupModuleRoleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModuleRoles|' as TABLE_NAME,'UserGroupId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupId] as nvarchar))),'"') as VALUE from auth.[UserGroupModuleRoles] where ltrim(rtrim(cast([UserGroupId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModuleRoles|' as TABLE_NAME,'AppModuleRoleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleRoleId] as nvarchar))),'"') as VALUE from auth.[UserGroupModuleRoles] where ltrim(rtrim(cast([AppModuleRoleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModuleRoles|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserGroupModuleRoles] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModules|' as TABLE_NAME,'UserGroupModuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupModuleId] as nvarchar))),'"') as VALUE from auth.[UserGroupModules] where ltrim(rtrim(cast([UserGroupModuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModules|' as TABLE_NAME,'AppModuleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AppModuleId] as nvarchar))),'"') as VALUE from auth.[UserGroupModules] where ltrim(rtrim(cast([AppModuleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModules|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserGroupModules] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroupModules|' as TABLE_NAME,'UserGroupId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupId] as nvarchar))),'"') as VALUE from auth.[UserGroupModules] where ltrim(rtrim(cast([UserGroupId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroups|' as TABLE_NAME,'UserGroupId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupId] as nvarchar))),'"') as VALUE from auth.[UserGroups] where ltrim(rtrim(cast([UserGroupId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroups|' as TABLE_NAME,'ApplyNumericPresedence|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ApplyNumericPresedence] as nvarchar))),'"') as VALUE from auth.[UserGroups] where ltrim(rtrim(cast([ApplyNumericPresedence] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroups|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserGroups] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroups|' as TABLE_NAME,'UserGroupName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupName] as nvarchar))),'"') as VALUE from auth.[UserGroups] where ltrim(rtrim(cast([UserGroupName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserGroups|' as TABLE_NAME,'DefaultAppModuleRoleId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DefaultAppModuleRoleId] as nvarchar))),'"') as VALUE from auth.[UserGroups] where ltrim(rtrim(cast([DefaultAppModuleRoleId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'UserPhoneNumberId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserPhoneNumberId] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([UserPhoneNumberId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'AreaCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([AreaCode] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([AreaCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'CountryCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([CountryCode] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([CountryCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'IsVerified|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsVerified] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([IsVerified] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'LocationId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LocationId] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([LocationId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'PhoneNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PhoneNumber] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([PhoneNumber] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'PhoneTypeId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PhoneTypeId] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([PhoneTypeId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserPhoneNumbers|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[UserPhoneNumbers] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileGroups|' as TABLE_NAME,'UserGroupId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserGroupId] as nvarchar))),'"') as VALUE from auth.[UserProfileGroups] where ltrim(rtrim(cast([UserGroupId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileGroups|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[UserProfileGroups] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileGroups|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserProfileGroups] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'Designation|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Designation] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([Designation] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'FirstName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([FirstName] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([FirstName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'IsBlocked|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsBlocked] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([IsBlocked] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'IsEnabled|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsEnabled] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([IsEnabled] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'IsRegister|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsRegister] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([IsRegister] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'LastName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastName] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([LastName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'MiddleName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([MiddleName] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([MiddleName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'PasswordHash|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PasswordHash] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([PasswordHash] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'PasswordSalt|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PasswordSalt] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([PasswordSalt] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'TemproryKeyCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([TemproryKeyCode] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([TemproryKeyCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'UserName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserName] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([UserName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'UserProfileImage|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileImage] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([UserProfileImage] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'LastLoginDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastLoginDate] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([LastLoginDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'Gender|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Gender] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([Gender] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'DOB|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DOB] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([DOB] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'Languages|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Languages] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([Languages] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'IsVerified|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsVerified] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([IsVerified] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'PrimaryEmail|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrimaryEmail] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([PrimaryEmail] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'PrimaryPhoneNumber|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PrimaryPhoneNumber] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([PrimaryPhoneNumber] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'ProviderCode|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ProviderCode] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([ProviderCode] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'Title|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Title] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([Title] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'ActivationDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ActivationDate] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([ActivationDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'IsForcedLogout|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsForcedLogout] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([IsForcedLogout] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfiles|' as TABLE_NAME,'LastLogoutDate|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([LastLogoutDate] as nvarchar))),'"') as VALUE from auth.[UserProfiles] where ltrim(rtrim(cast([LastLogoutDate] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSecretAnswers|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[UserProfileSecretAnswers] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSecretAnswers|' as TABLE_NAME,'SecretQuestionId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SecretQuestionId] as nvarchar))),'"') as VALUE from auth.[UserProfileSecretAnswers] where ltrim(rtrim(cast([SecretQuestionId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSecretAnswers|' as TABLE_NAME,'Answer|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Answer] as nvarchar))),'"') as VALUE from auth.[UserProfileSecretAnswers] where ltrim(rtrim(cast([Answer] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSecretAnswers|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserProfileSecretAnswers] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSettings|' as TABLE_NAME,'UserProfileSettingId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileSettingId] as nvarchar))),'"') as VALUE from auth.[UserProfileSettings] where ltrim(rtrim(cast([UserProfileSettingId] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSettings|' as TABLE_NAME,'IsActive|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from auth.[UserProfileSettings] where ltrim(rtrim(cast([IsActive] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSettings|' as TABLE_NAME,'SettingName|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SettingName] as nvarchar))),'"') as VALUE from auth.[UserProfileSettings] where ltrim(rtrim(cast([SettingName] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSettings|' as TABLE_NAME,'SettingValue|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([SettingValue] as nvarchar))),'"') as VALUE from auth.[UserProfileSettings] where ltrim(rtrim(cast([SettingValue] as nvarchar))) like @SearchPredicate) a union 
select top 40 * from  (select distinct  'auth|' as TABLE_SCHEMA,'UserProfileSettings|' as TABLE_NAME,'UserProfileId|' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UserProfileId] as nvarchar))),'"') as VALUE from auth.[UserProfileSettings] where ltrim(rtrim(cast([UserProfileId] as nvarchar))) like @SearchPredicate) a


select * from auth.UserProfiles where UserProfileID = '12889' order by UserProfileID
select * from auth.UserGroups where UserGroupID in (select UserGroupID from UserProfileGroups where UserProfileID in (
select * from auth.UserProfileGroups where UserProfileID = '12889'  order by UserProfileID
select * from auth.UserProfileSettings where UserProfileID = '12889'  order by UserProfileID
select * from auth.UserProfileSecretAnswers where UserProfileID = '12889'  order by UserProfileID

select firstname, count(*)  from auth.UserProfiles group by FirstName having count(*) > 5 order by 2 desc

select firstname, lastname, providercode, count(*) from auth.UserProfiles where firstname like 'Michael' group by firstname, lastname, providercode having 4 > 2 order by 4 desc 

select * from auth.UserProfiles where firstname like 'dianne' and lastname like 'cooper'

select * from auth.UserProfiles where FirstName = 'Keayana'
select * from auth.UserProfiles where FirstName = 'Ernest' and LastName = 'Golden'
select * from auth.UserProfiles where FirstName = 'sabri'

select * from auth.UserGroups where UserGroupID in (select UserGroupID from auth.UserProfileGroups  where UserProfileID in ('23881','23868', '25646' ) )
select * from auth.UserProfiles where UserProfileID in ('23881','23868', '25646' ) order by UserProfileID
select * from auth.UserProfileGroups where UserProfileID in ('23881','23868', '25646' ) order by UserProfileID
select * from auth.UserProfileSettings where UserProfileID in ('23881','23868', '25646' ) order by UserProfileID
select * from auth.UserProfileSecretAnswers where UserProfileID in ('23881','23868', '25646' ) order by UserProfileID
