select * from information_schema.columns where table_name like '%wallet%'

select distinct table_schema from information_schema.columns where table_name like '%wallet%'
/*
dbo
elig
otccatalog
*/

select * from information_schema.columns where table_name like '%wallet%' order by table_schema, table_name


select
'select top 100 * from
(' +
'select distinct  ' 
+''''+TABLE_SCHEMA+''''+' as TABLE_SCHEMA,' 
+''''+ TABLE_NAME+'''' + ' as TABLE_NAME,' 
+''''+ COLUMN_NAME +''''+ ' as COLUMN_NAME,' 
+ 'QUOTENAME(ltrim(rtrim(cast(' +'['+ COLUMN_NAME+']' + ' as nvarchar))),' + '''"'''+') as VALUE from ' 
+ TABLE_SCHEMA +'.'+ '['+TABLE_NAME+']' +
') a union '
from  information_Schema.COLUMNS
where TABLE_NAME IN (select distinct table_name from information_schema.columns where table_name like '%wallet%' and table_schema in ('dbo', 'elig','otccatalog')) 
--and TABLE_SCHEMA IN ('insurance')
and DATA_TYPE IN ('float','bigint','bit','datetime','nvarchar','varchar')
and COLUMN_NAME NOT IN ('CreateUser', 'ModifyUser', 'CreateDate', 'ModifyDate')


select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'ID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ID] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'WalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletName] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'Code' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Code] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'WalletDisplayName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletDisplayName] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'Vendor' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Vendor] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'Amount' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Amount] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'OTC_Wallet' as TABLE_NAME,'Isactive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Isactive] as nvarchar))),'"') as VALUE from elig.[OTC_Wallet]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'WalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletName] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'WalletDescription' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletDescription] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'ShowonWeb' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ShowonWeb] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletCode] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'WalletSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletSource] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'DisplayWalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DisplayWalletName] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'Wallets' as TABLE_NAME,'ColorCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ColorCode] as nvarchar))),'"') as VALUE from otccatalog.[Wallets]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItems' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItems]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItems' as TABLE_NAME,'NationsId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NationsId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItems]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItems' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItems]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItems' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletItems]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItemsHistory' as TABLE_NAME,'WalletItemHistoryId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemHistoryId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItemsHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItemsHistory' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItemsHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItemsHistory' as TABLE_NAME,'NationsId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NationsId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItemsHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItemsHistory' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from otccatalog.[WalletItemsHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItemsHistory' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletItemsHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletItemsHistory' as TABLE_NAME,'Action' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Action] as nvarchar))),'"') as VALUE from otccatalog.[WalletItemsHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverrides' as TABLE_NAME,'WalletOverrideId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletOverrideId] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverrides' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverrides' as TABLE_NAME,'OverrideItemStandardData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideItemStandardData] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverrides' as TABLE_NAME,'OverrideStockStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideStockStatusCode] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverrides' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'WalltetOverridesHistoryId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalltetOverridesHistoryId] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'WalletOverrideId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletOverrideId] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'OverrideItemStandardData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideItemStandardData] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'OverrideStockStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideStockStatusCode] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletOverridesHistory' as TABLE_NAME,'Action' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Action] as nvarchar))),'"') as VALUE from otccatalog.[WalletOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'WalletPlanId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'InsuranceCarrierId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'InsuranceHealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'PlanWalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanWalletName] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlans' as TABLE_NAME,'DisplayWalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DisplayWalletName] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlans]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'UPC12' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UPC12] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'Status' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Status] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'Description' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Description] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'NH ID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NH ID] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'Stock' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Stock] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'Restock Date' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Restock Date] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletLoad' as TABLE_NAME,'Source' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Source] as nvarchar))),'"') as VALUE from dbo.[walletLoad]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'WalletName (Sheet Name)' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletName (Sheet Name)] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'WalletCode ' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletCode ] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Site Display Name (Austin to ADD)' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Site Display Name (Austin to ADD)] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'WalletSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletSource] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Wallet Status' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Wallet Status] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'InsuranceCarrierName (By Nithin)' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierName (By Nithin)] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Plans (Taken From Benefit Rules Sheet)' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Plans (Taken From Benefit Rules Sheet)] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Comments' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Comments] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'F10' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([F10] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'F11' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([F11] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'F12' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([F12] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Carrier' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Carrier] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Member Group' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Member Group] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Group Number' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Group Number] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'InComm Return (Display name)' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InComm Return (Display name)] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Mapped Wallet' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Mapped Wallet] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'Additional Wallet' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Additional Wallet] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'MasterWalletCodes' as TABLE_NAME,'UI Name' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UI Name] as nvarchar))),'"') as VALUE from dbo.[MasterWalletCodes]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'WalletPlansHistoryId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlansHistoryId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'WalletPlanId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'InsuranceCarrierId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'InsuranceHealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'PlanWalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([PlanWalletName] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlansHistory' as TABLE_NAME,'Action' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Action] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlansHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverrides' as TABLE_NAME,'WalletPlanOverrideId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanOverrideId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverrides' as TABLE_NAME,'WalletPlanId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverrides' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverrides' as TABLE_NAME,'OverrideItemStandardData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideItemStandardData] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverrides' as TABLE_NAME,'OverrideStockStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideStockStatusCode] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverrides' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'WalletPlanOverridesHistoryid' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanOverridesHistoryid] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'WalletPlanOverrideId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanOverrideId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'WalletPlanId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletPlanId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'OverrideItemStandardData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideItemStandardData] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'OverrideStockStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideStockStatusCode] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'WalletPlanOverridesHistory' as TABLE_NAME,'Action' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Action] as nvarchar))),'"') as VALUE from otccatalog.[WalletPlanOverridesHistory]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'WalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletName] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'WalletDescription' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletDescription] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletCode] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'WalletSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletSource] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'DisplayWalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([DisplayWalletName] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_Wallets' as TABLE_NAME,'InsuranceHealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID] as nvarchar))),'"') as VALUE from dbo.[votc_Wallets]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'UPC12' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([UPC12] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'Status' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Status] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'Description' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Description] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'NH ID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NH ID] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'Stock' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Stock] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'walletload1' as TABLE_NAME,'Restock Date' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([Restock Date] as nvarchar))),'"') as VALUE from dbo.[walletload1]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletPlans' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[votc_WalletPlans]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletPlans' as TABLE_NAME,'InsuranceCarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierID] as nvarchar))),'"') as VALUE from dbo.[votc_WalletPlans]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletItems' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from dbo.[votc_WalletItems]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletItems' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[votc_WalletItems]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletItems' as TABLE_NAME,'NationsId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([NationsId] as nvarchar))),'"') as VALUE from dbo.[votc_WalletItems]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletOverrides' as TABLE_NAME,'WalletItemId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletItemId] as nvarchar))),'"') as VALUE from dbo.[votc_WalletOverrides]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletOverrides' as TABLE_NAME,'OverrideItemStandardData' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideItemStandardData] as nvarchar))),'"') as VALUE from dbo.[votc_WalletOverrides]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletOverrides' as TABLE_NAME,'OverrideStockStatusCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverrideStockStatusCode] as nvarchar))),'"') as VALUE from dbo.[votc_WalletOverrides]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletOverrides' as TABLE_NAME,'OverridePrice' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([OverridePrice] as nvarchar))),'"') as VALUE from dbo.[votc_WalletOverrides]) a union 
select top 100 * from  (select distinct  'dbo' as TABLE_SCHEMA,'votc_WalletOverrides' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from dbo.[votc_WalletOverrides]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'InsuranceCarrierId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierId] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'InsuranceCarrierName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierName] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'InsuranceHealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'HealthPlanName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([HealthPlanName] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'WalletId' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletId] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'WalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletName] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'WalletCode' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletCode] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'WalletSource' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletSource] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'WalltMaps' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalltMaps] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'otccatalog' as TABLE_SCHEMA,'GetPlanWalletMap' as TABLE_NAME,'WalltAdds' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalltAdds] as nvarchar))),'"') as VALUE from otccatalog.[GetPlanWalletMap]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'HealthPlanWallet' as TABLE_NAME,'ID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([ID] as nvarchar))),'"') as VALUE from elig.[HealthPlanWallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'HealthPlanWallet' as TABLE_NAME,'WalletName' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([WalletName] as nvarchar))),'"') as VALUE from elig.[HealthPlanWallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'HealthPlanWallet' as TABLE_NAME,'InsuranceCarrierID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceCarrierID] as nvarchar))),'"') as VALUE from elig.[HealthPlanWallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'HealthPlanWallet' as TABLE_NAME,'InsuranceHealthPlanID' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([InsuranceHealthPlanID] as nvarchar))),'"') as VALUE from elig.[HealthPlanWallet]) a union 
select top 100 * from  (select distinct  'elig' as TABLE_SCHEMA,'HealthPlanWallet' as TABLE_NAME,'IsActive' as COLUMN_NAME,QUOTENAME(ltrim(rtrim(cast([IsActive] as nvarchar))),'"') as VALUE from elig.[HealthPlanWallet]) a